version: "3"

tasks:
  build:
    desc: Build the CLI binary
    cmds:
      - go build -o /dev/null main.go

  install:
    desc: Install the CLI binary
    cmds:
      - go install

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  coverage:
    desc: Run tests with coverage
    cmds:
      - go test --cover ./...

  coverage-html:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  open-coverage-html:
    desc: Generate and open HTML coverage report
    deps:
      - coverage-html
    cmds:
      - open coverage.html

  pull-swagger:
    desc: Pull Jira API swagger definitions (Platform and Software)
    preconditions:
      - sh: command -v curl
        msg: "curl is required but not installed"
    cmds:
      - curl -o swagger.json -sSL https://dac-static.atlassian.com/cloud/confluence/openapi-v2.v3.json

  generate-swagger:
    desc: Generate Go client from swagger_confluence.json using openapi-generator
    preconditions:
      - sh: command -v openapi-generator
        msg: "openapi-generator is required but not installed. Install with: brew install openapi-generator"
      - sh: test -f swagger_confluence.json
        msg: "swagger_confluence.json not found. Run 'task pull-swagger-confluence' first"
    cmds:
      - rm -rf swagger_confluence
      - >-
        openapi-generator generate -i swagger_confluence.json -g go -o swagger_confluence --package-name swagger_confluence --additional-properties=isGoSubmodule=true --git-user-id alexhokl --git-repo-id jira-cli
      - go mod tidy
