/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the SpacePermissionAssignment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpacePermissionAssignment{}

// SpacePermissionAssignment struct for SpacePermissionAssignment
type SpacePermissionAssignment struct {
	// ID of the space permission.
	Id *string `json:"id,omitempty"`
	Principal *SpacePermissionAssignmentPrincipal `json:"principal,omitempty"`
	Operation *SpacePermissionAssignmentOperation `json:"operation,omitempty"`
}

// NewSpacePermissionAssignment instantiates a new SpacePermissionAssignment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpacePermissionAssignment() *SpacePermissionAssignment {
	this := SpacePermissionAssignment{}
	return &this
}

// NewSpacePermissionAssignmentWithDefaults instantiates a new SpacePermissionAssignment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpacePermissionAssignmentWithDefaults() *SpacePermissionAssignment {
	this := SpacePermissionAssignment{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SpacePermissionAssignment) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermissionAssignment) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SpacePermissionAssignment) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SpacePermissionAssignment) SetId(v string) {
	o.Id = &v
}

// GetPrincipal returns the Principal field value if set, zero value otherwise.
func (o *SpacePermissionAssignment) GetPrincipal() SpacePermissionAssignmentPrincipal {
	if o == nil || IsNil(o.Principal) {
		var ret SpacePermissionAssignmentPrincipal
		return ret
	}
	return *o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermissionAssignment) GetPrincipalOk() (*SpacePermissionAssignmentPrincipal, bool) {
	if o == nil || IsNil(o.Principal) {
		return nil, false
	}
	return o.Principal, true
}

// HasPrincipal returns a boolean if a field has been set.
func (o *SpacePermissionAssignment) HasPrincipal() bool {
	if o != nil && !IsNil(o.Principal) {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given SpacePermissionAssignmentPrincipal and assigns it to the Principal field.
func (o *SpacePermissionAssignment) SetPrincipal(v SpacePermissionAssignmentPrincipal) {
	o.Principal = &v
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *SpacePermissionAssignment) GetOperation() SpacePermissionAssignmentOperation {
	if o == nil || IsNil(o.Operation) {
		var ret SpacePermissionAssignmentOperation
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermissionAssignment) GetOperationOk() (*SpacePermissionAssignmentOperation, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *SpacePermissionAssignment) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given SpacePermissionAssignmentOperation and assigns it to the Operation field.
func (o *SpacePermissionAssignment) SetOperation(v SpacePermissionAssignmentOperation) {
	o.Operation = &v
}

func (o SpacePermissionAssignment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpacePermissionAssignment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Principal) {
		toSerialize["principal"] = o.Principal
	}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	return toSerialize, nil
}

type NullableSpacePermissionAssignment struct {
	value *SpacePermissionAssignment
	isSet bool
}

func (v NullableSpacePermissionAssignment) Get() *SpacePermissionAssignment {
	return v.value
}

func (v *NullableSpacePermissionAssignment) Set(val *SpacePermissionAssignment) {
	v.value = val
	v.isSet = true
}

func (v NullableSpacePermissionAssignment) IsSet() bool {
	return v.isSet
}

func (v *NullableSpacePermissionAssignment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpacePermissionAssignment(val *SpacePermissionAssignment) *NullableSpacePermissionAssignment {
	return &NullableSpacePermissionAssignment{value: val, isSet: true}
}

func (v NullableSpacePermissionAssignment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpacePermissionAssignment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


