/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the UpdateSpaceRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSpaceRoleResponse{}

// UpdateSpaceRoleResponse struct for UpdateSpaceRoleResponse
type UpdateSpaceRoleResponse struct {
	// Id of the space role
	Id *string `json:"id,omitempty"`
	Type *RoleType `json:"type,omitempty"`
	// Name of the space role
	Name *string `json:"name,omitempty"`
	// Description for the space role
	Description *string `json:"description,omitempty"`
	// Id of the task to update the space permissions associated with the space role
	TaskId *string `json:"taskId,omitempty"`
}

// NewUpdateSpaceRoleResponse instantiates a new UpdateSpaceRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSpaceRoleResponse() *UpdateSpaceRoleResponse {
	this := UpdateSpaceRoleResponse{}
	return &this
}

// NewUpdateSpaceRoleResponseWithDefaults instantiates a new UpdateSpaceRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSpaceRoleResponseWithDefaults() *UpdateSpaceRoleResponse {
	this := UpdateSpaceRoleResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateSpaceRoleResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSpaceRoleResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateSpaceRoleResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdateSpaceRoleResponse) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpdateSpaceRoleResponse) GetType() RoleType {
	if o == nil || IsNil(o.Type) {
		var ret RoleType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSpaceRoleResponse) GetTypeOk() (*RoleType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpdateSpaceRoleResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given RoleType and assigns it to the Type field.
func (o *UpdateSpaceRoleResponse) SetType(v RoleType) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateSpaceRoleResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSpaceRoleResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateSpaceRoleResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateSpaceRoleResponse) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateSpaceRoleResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSpaceRoleResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateSpaceRoleResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateSpaceRoleResponse) SetDescription(v string) {
	o.Description = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *UpdateSpaceRoleResponse) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSpaceRoleResponse) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *UpdateSpaceRoleResponse) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *UpdateSpaceRoleResponse) SetTaskId(v string) {
	o.TaskId = &v
}

func (o UpdateSpaceRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSpaceRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	return toSerialize, nil
}

type NullableUpdateSpaceRoleResponse struct {
	value *UpdateSpaceRoleResponse
	isSet bool
}

func (v NullableUpdateSpaceRoleResponse) Get() *UpdateSpaceRoleResponse {
	return v.value
}

func (v *NullableUpdateSpaceRoleResponse) Set(val *UpdateSpaceRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSpaceRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSpaceRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSpaceRoleResponse(val *UpdateSpaceRoleResponse) *NullableUpdateSpaceRoleResponse {
	return &NullableUpdateSpaceRoleResponse{value: val, isSet: true}
}

func (v NullableUpdateSpaceRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSpaceRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


