/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PutPageClassificationLevelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutPageClassificationLevelRequest{}

// PutPageClassificationLevelRequest struct for PutPageClassificationLevelRequest
type PutPageClassificationLevelRequest struct {
	// The ID of the classification level.
	Id string `json:"id"`
	// Status of the content.
	Status string `json:"status"`
}

type _PutPageClassificationLevelRequest PutPageClassificationLevelRequest

// NewPutPageClassificationLevelRequest instantiates a new PutPageClassificationLevelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutPageClassificationLevelRequest(id string, status string) *PutPageClassificationLevelRequest {
	this := PutPageClassificationLevelRequest{}
	this.Id = id
	this.Status = status
	return &this
}

// NewPutPageClassificationLevelRequestWithDefaults instantiates a new PutPageClassificationLevelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutPageClassificationLevelRequestWithDefaults() *PutPageClassificationLevelRequest {
	this := PutPageClassificationLevelRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PutPageClassificationLevelRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PutPageClassificationLevelRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PutPageClassificationLevelRequest) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *PutPageClassificationLevelRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PutPageClassificationLevelRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PutPageClassificationLevelRequest) SetStatus(v string) {
	o.Status = v
}

func (o PutPageClassificationLevelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutPageClassificationLevelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PutPageClassificationLevelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutPageClassificationLevelRequest := _PutPageClassificationLevelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutPageClassificationLevelRequest)

	if err != nil {
		return err
	}

	*o = PutPageClassificationLevelRequest(varPutPageClassificationLevelRequest)

	return err
}

type NullablePutPageClassificationLevelRequest struct {
	value *PutPageClassificationLevelRequest
	isSet bool
}

func (v NullablePutPageClassificationLevelRequest) Get() *PutPageClassificationLevelRequest {
	return v.value
}

func (v *NullablePutPageClassificationLevelRequest) Set(val *PutPageClassificationLevelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutPageClassificationLevelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutPageClassificationLevelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutPageClassificationLevelRequest(val *PutPageClassificationLevelRequest) *NullablePutPageClassificationLevelRequest {
	return &NullablePutPageClassificationLevelRequest{value: val, isSet: true}
}

func (v NullablePutPageClassificationLevelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutPageClassificationLevelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


