/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"fmt"
)

// AccountStatus The account status of the user.
type AccountStatus string

// List of AccountStatus
const (
	ACCOUNT_STATUS_ACTIVE   AccountStatus = "active"
	ACCOUNT_STATUS_INACTIVE AccountStatus = "inactive"
	ACCOUNT_STATUS_CLOSED   AccountStatus = "closed"
	ACCOUNT_STATUS_UNKNOWN  AccountStatus = "unknown"
)

// All allowed values of AccountStatus enum
var AllowedAccountStatusEnumValues = []AccountStatus{
	"active",
	"inactive",
	"closed",
	"unknown",
}

func (v *AccountStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AccountStatus(value)
	for _, existing := range AllowedAccountStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AccountStatus", value)
}

// NewAccountStatusFromValue returns a pointer to a valid AccountStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAccountStatusFromValue(v string) (*AccountStatus, error) {
	ev := AccountStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AccountStatus: valid values are %v", v, AllowedAccountStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AccountStatus) IsValid() bool {
	for _, existing := range AllowedAccountStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AccountStatus value
func (v AccountStatus) Ptr() *AccountStatus {
	return &v
}

type NullableAccountStatus struct {
	value *AccountStatus
	isSet bool
}

func (v NullableAccountStatus) Get() *AccountStatus {
	return v.value
}

func (v *NullableAccountStatus) Set(val *AccountStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountStatus(val *AccountStatus) *NullableAccountStatus {
	return &NullableAccountStatus{value: val, isSet: true}
}

func (v NullableAccountStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
