/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the Principal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Principal{}

// Principal The principal of the role assignment.
type Principal struct {
	PrincipalType *PrincipalType `json:"principalType,omitempty"`
	// The principal ID.
	PrincipalId *string `json:"principalId,omitempty"`
}

// NewPrincipal instantiates a new Principal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipal() *Principal {
	this := Principal{}
	return &this
}

// NewPrincipalWithDefaults instantiates a new Principal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalWithDefaults() *Principal {
	this := Principal{}
	return &this
}

// GetPrincipalType returns the PrincipalType field value if set, zero value otherwise.
func (o *Principal) GetPrincipalType() PrincipalType {
	if o == nil || IsNil(o.PrincipalType) {
		var ret PrincipalType
		return ret
	}
	return *o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetPrincipalTypeOk() (*PrincipalType, bool) {
	if o == nil || IsNil(o.PrincipalType) {
		return nil, false
	}
	return o.PrincipalType, true
}

// HasPrincipalType returns a boolean if a field has been set.
func (o *Principal) HasPrincipalType() bool {
	if o != nil && !IsNil(o.PrincipalType) {
		return true
	}

	return false
}

// SetPrincipalType gets a reference to the given PrincipalType and assigns it to the PrincipalType field.
func (o *Principal) SetPrincipalType(v PrincipalType) {
	o.PrincipalType = &v
}

// GetPrincipalId returns the PrincipalId field value if set, zero value otherwise.
func (o *Principal) GetPrincipalId() string {
	if o == nil || IsNil(o.PrincipalId) {
		var ret string
		return ret
	}
	return *o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetPrincipalIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrincipalId) {
		return nil, false
	}
	return o.PrincipalId, true
}

// HasPrincipalId returns a boolean if a field has been set.
func (o *Principal) HasPrincipalId() bool {
	if o != nil && !IsNil(o.PrincipalId) {
		return true
	}

	return false
}

// SetPrincipalId gets a reference to the given string and assigns it to the PrincipalId field.
func (o *Principal) SetPrincipalId(v string) {
	o.PrincipalId = &v
}

func (o Principal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Principal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrincipalType) {
		toSerialize["principalType"] = o.PrincipalType
	}
	if !IsNil(o.PrincipalId) {
		toSerialize["principalId"] = o.PrincipalId
	}
	return toSerialize, nil
}

type NullablePrincipal struct {
	value *Principal
	isSet bool
}

func (v NullablePrincipal) Get() *Principal {
	return v.value
}

func (v *NullablePrincipal) Set(val *Principal) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipal) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipal(val *Principal) *NullablePrincipal {
	return &NullablePrincipal{value: val, isSet: true}
}

func (v NullablePrincipal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


