/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"time"
)

// checks if the CustomContentSingle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomContentSingle{}

// CustomContentSingle struct for CustomContentSingle
type CustomContentSingle struct {
	// ID of the custom content.
	Id *string `json:"id,omitempty"`
	// The type of custom content.
	Type *string `json:"type,omitempty"`
	Status *ContentStatus `json:"status,omitempty"`
	// Title of the custom content.
	Title *string `json:"title,omitempty"`
	// ID of the space the custom content is in.  Note: This is always returned, regardless of if the custom content has a container that is a space.
	SpaceId *string `json:"spaceId,omitempty"`
	// ID of the containing page.  Note: This is only returned if the custom content has a container that is a page.
	PageId *string `json:"pageId,omitempty"`
	// ID of the containing blog post.  Note: This is only returned if the custom content has a container that is a blog post.
	BlogPostId *string `json:"blogPostId,omitempty"`
	// ID of the containing custom content.  Note: This is only returned if the custom content has a container that is custom content.
	CustomContentId *string `json:"customContentId,omitempty"`
	// The account ID of the user who created this custom content originally.
	AuthorId *string `json:"authorId,omitempty"`
	// Date and time when the custom content was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Version *Version `json:"version,omitempty"`
	Labels *AttachmentSingleLabels `json:"labels,omitempty"`
	Properties *AttachmentSingleProperties `json:"properties,omitempty"`
	Operations *AttachmentSingleOperations `json:"operations,omitempty"`
	Versions *AttachmentSingleVersions `json:"versions,omitempty"`
	Body *CustomContentBodySingle `json:"body,omitempty"`
	Links *CustomContentLinks `json:"_links,omitempty"`
}

// NewCustomContentSingle instantiates a new CustomContentSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomContentSingle() *CustomContentSingle {
	this := CustomContentSingle{}
	return &this
}

// NewCustomContentSingleWithDefaults instantiates a new CustomContentSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomContentSingleWithDefaults() *CustomContentSingle {
	this := CustomContentSingle{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomContentSingle) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomContentSingle) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustomContentSingle) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CustomContentSingle) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CustomContentSingle) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CustomContentSingle) SetType(v string) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CustomContentSingle) GetStatus() ContentStatus {
	if o == nil || IsNil(o.Status) {
		var ret ContentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetStatusOk() (*ContentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CustomContentSingle) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ContentStatus and assigns it to the Status field.
func (o *CustomContentSingle) SetStatus(v ContentStatus) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CustomContentSingle) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CustomContentSingle) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CustomContentSingle) SetTitle(v string) {
	o.Title = &v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *CustomContentSingle) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *CustomContentSingle) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *CustomContentSingle) SetSpaceId(v string) {
	o.SpaceId = &v
}

// GetPageId returns the PageId field value if set, zero value otherwise.
func (o *CustomContentSingle) GetPageId() string {
	if o == nil || IsNil(o.PageId) {
		var ret string
		return ret
	}
	return *o.PageId
}

// GetPageIdOk returns a tuple with the PageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetPageIdOk() (*string, bool) {
	if o == nil || IsNil(o.PageId) {
		return nil, false
	}
	return o.PageId, true
}

// HasPageId returns a boolean if a field has been set.
func (o *CustomContentSingle) HasPageId() bool {
	if o != nil && !IsNil(o.PageId) {
		return true
	}

	return false
}

// SetPageId gets a reference to the given string and assigns it to the PageId field.
func (o *CustomContentSingle) SetPageId(v string) {
	o.PageId = &v
}

// GetBlogPostId returns the BlogPostId field value if set, zero value otherwise.
func (o *CustomContentSingle) GetBlogPostId() string {
	if o == nil || IsNil(o.BlogPostId) {
		var ret string
		return ret
	}
	return *o.BlogPostId
}

// GetBlogPostIdOk returns a tuple with the BlogPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetBlogPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlogPostId) {
		return nil, false
	}
	return o.BlogPostId, true
}

// HasBlogPostId returns a boolean if a field has been set.
func (o *CustomContentSingle) HasBlogPostId() bool {
	if o != nil && !IsNil(o.BlogPostId) {
		return true
	}

	return false
}

// SetBlogPostId gets a reference to the given string and assigns it to the BlogPostId field.
func (o *CustomContentSingle) SetBlogPostId(v string) {
	o.BlogPostId = &v
}

// GetCustomContentId returns the CustomContentId field value if set, zero value otherwise.
func (o *CustomContentSingle) GetCustomContentId() string {
	if o == nil || IsNil(o.CustomContentId) {
		var ret string
		return ret
	}
	return *o.CustomContentId
}

// GetCustomContentIdOk returns a tuple with the CustomContentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetCustomContentIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomContentId) {
		return nil, false
	}
	return o.CustomContentId, true
}

// HasCustomContentId returns a boolean if a field has been set.
func (o *CustomContentSingle) HasCustomContentId() bool {
	if o != nil && !IsNil(o.CustomContentId) {
		return true
	}

	return false
}

// SetCustomContentId gets a reference to the given string and assigns it to the CustomContentId field.
func (o *CustomContentSingle) SetCustomContentId(v string) {
	o.CustomContentId = &v
}

// GetAuthorId returns the AuthorId field value if set, zero value otherwise.
func (o *CustomContentSingle) GetAuthorId() string {
	if o == nil || IsNil(o.AuthorId) {
		var ret string
		return ret
	}
	return *o.AuthorId
}

// GetAuthorIdOk returns a tuple with the AuthorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetAuthorIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorId) {
		return nil, false
	}
	return o.AuthorId, true
}

// HasAuthorId returns a boolean if a field has been set.
func (o *CustomContentSingle) HasAuthorId() bool {
	if o != nil && !IsNil(o.AuthorId) {
		return true
	}

	return false
}

// SetAuthorId gets a reference to the given string and assigns it to the AuthorId field.
func (o *CustomContentSingle) SetAuthorId(v string) {
	o.AuthorId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CustomContentSingle) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CustomContentSingle) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CustomContentSingle) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CustomContentSingle) GetVersion() Version {
	if o == nil || IsNil(o.Version) {
		var ret Version
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetVersionOk() (*Version, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CustomContentSingle) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given Version and assigns it to the Version field.
func (o *CustomContentSingle) SetVersion(v Version) {
	o.Version = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CustomContentSingle) GetLabels() AttachmentSingleLabels {
	if o == nil || IsNil(o.Labels) {
		var ret AttachmentSingleLabels
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetLabelsOk() (*AttachmentSingleLabels, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CustomContentSingle) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given AttachmentSingleLabels and assigns it to the Labels field.
func (o *CustomContentSingle) SetLabels(v AttachmentSingleLabels) {
	o.Labels = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CustomContentSingle) GetProperties() AttachmentSingleProperties {
	if o == nil || IsNil(o.Properties) {
		var ret AttachmentSingleProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetPropertiesOk() (*AttachmentSingleProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CustomContentSingle) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given AttachmentSingleProperties and assigns it to the Properties field.
func (o *CustomContentSingle) SetProperties(v AttachmentSingleProperties) {
	o.Properties = &v
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *CustomContentSingle) GetOperations() AttachmentSingleOperations {
	if o == nil || IsNil(o.Operations) {
		var ret AttachmentSingleOperations
		return ret
	}
	return *o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetOperationsOk() (*AttachmentSingleOperations, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *CustomContentSingle) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given AttachmentSingleOperations and assigns it to the Operations field.
func (o *CustomContentSingle) SetOperations(v AttachmentSingleOperations) {
	o.Operations = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *CustomContentSingle) GetVersions() AttachmentSingleVersions {
	if o == nil || IsNil(o.Versions) {
		var ret AttachmentSingleVersions
		return ret
	}
	return *o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetVersionsOk() (*AttachmentSingleVersions, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *CustomContentSingle) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given AttachmentSingleVersions and assigns it to the Versions field.
func (o *CustomContentSingle) SetVersions(v AttachmentSingleVersions) {
	o.Versions = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CustomContentSingle) GetBody() CustomContentBodySingle {
	if o == nil || IsNil(o.Body) {
		var ret CustomContentBodySingle
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetBodyOk() (*CustomContentBodySingle, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CustomContentSingle) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given CustomContentBodySingle and assigns it to the Body field.
func (o *CustomContentSingle) SetBody(v CustomContentBodySingle) {
	o.Body = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CustomContentSingle) GetLinks() CustomContentLinks {
	if o == nil || IsNil(o.Links) {
		var ret CustomContentLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomContentSingle) GetLinksOk() (*CustomContentLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CustomContentSingle) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CustomContentLinks and assigns it to the Links field.
func (o *CustomContentSingle) SetLinks(v CustomContentLinks) {
	o.Links = &v
}

func (o CustomContentSingle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomContentSingle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.SpaceId) {
		toSerialize["spaceId"] = o.SpaceId
	}
	if !IsNil(o.PageId) {
		toSerialize["pageId"] = o.PageId
	}
	if !IsNil(o.BlogPostId) {
		toSerialize["blogPostId"] = o.BlogPostId
	}
	if !IsNil(o.CustomContentId) {
		toSerialize["customContentId"] = o.CustomContentId
	}
	if !IsNil(o.AuthorId) {
		toSerialize["authorId"] = o.AuthorId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCustomContentSingle struct {
	value *CustomContentSingle
	isSet bool
}

func (v NullableCustomContentSingle) Get() *CustomContentSingle {
	return v.value
}

func (v *NullableCustomContentSingle) Set(val *CustomContentSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomContentSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomContentSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomContentSingle(val *CustomContentSingle) *NullableCustomContentSingle {
	return &NullableCustomContentSingle{value: val, isSet: true}
}

func (v NullableCustomContentSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomContentSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


