/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBulkUserLookupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBulkUserLookupRequest{}

// CreateBulkUserLookupRequest struct for CreateBulkUserLookupRequest
type CreateBulkUserLookupRequest struct {
	// List of accountIds to retrieve user info for.
	AccountIds []string `json:"accountIds"`
}

type _CreateBulkUserLookupRequest CreateBulkUserLookupRequest

// NewCreateBulkUserLookupRequest instantiates a new CreateBulkUserLookupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBulkUserLookupRequest(accountIds []string) *CreateBulkUserLookupRequest {
	this := CreateBulkUserLookupRequest{}
	this.AccountIds = accountIds
	return &this
}

// NewCreateBulkUserLookupRequestWithDefaults instantiates a new CreateBulkUserLookupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBulkUserLookupRequestWithDefaults() *CreateBulkUserLookupRequest {
	this := CreateBulkUserLookupRequest{}
	return &this
}

// GetAccountIds returns the AccountIds field value
func (o *CreateBulkUserLookupRequest) GetAccountIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AccountIds
}

// GetAccountIdsOk returns a tuple with the AccountIds field value
// and a boolean to check if the value has been set.
func (o *CreateBulkUserLookupRequest) GetAccountIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountIds, true
}

// SetAccountIds sets field value
func (o *CreateBulkUserLookupRequest) SetAccountIds(v []string) {
	o.AccountIds = v
}

func (o CreateBulkUserLookupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBulkUserLookupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountIds"] = o.AccountIds
	return toSerialize, nil
}

func (o *CreateBulkUserLookupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBulkUserLookupRequest := _CreateBulkUserLookupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBulkUserLookupRequest)

	if err != nil {
		return err
	}

	*o = CreateBulkUserLookupRequest(varCreateBulkUserLookupRequest)

	return err
}

type NullableCreateBulkUserLookupRequest struct {
	value *CreateBulkUserLookupRequest
	isSet bool
}

func (v NullableCreateBulkUserLookupRequest) Get() *CreateBulkUserLookupRequest {
	return v.value
}

func (v *NullableCreateBulkUserLookupRequest) Set(val *CreateBulkUserLookupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBulkUserLookupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBulkUserLookupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBulkUserLookupRequest(val *CreateBulkUserLookupRequest) *NullableCreateBulkUserLookupRequest {
	return &NullableCreateBulkUserLookupRequest{value: val, isSet: true}
}

func (v NullableCreateBulkUserLookupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBulkUserLookupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


