/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"fmt"
)

// CustomContentSortOrder The sort fields for custom content. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
type CustomContentSortOrder string

// List of CustomContentSortOrder
const (
	CUSTOM_CONTENT_SORT_ORDER_ID                 CustomContentSortOrder = "id"
	CUSTOM_CONTENT_SORT_ORDER_ID_DESC            CustomContentSortOrder = "-id"
	CUSTOM_CONTENT_SORT_ORDER_CREATED_DATE       CustomContentSortOrder = "created-date"
	CUSTOM_CONTENT_SORT_ORDER_CREATED_DATE_DESC  CustomContentSortOrder = "-created-date"
	CUSTOM_CONTENT_SORT_ORDER_MODIFIED_DATE      CustomContentSortOrder = "modified-date"
	CUSTOM_CONTENT_SORT_ORDER_MODIFIED_DATE_DESC CustomContentSortOrder = "-modified-date"
	CUSTOM_CONTENT_SORT_ORDER_TITLE              CustomContentSortOrder = "title"
	CUSTOM_CONTENT_SORT_ORDER_TITLE_DESC         CustomContentSortOrder = "-title"
)

// All allowed values of CustomContentSortOrder enum
var AllowedCustomContentSortOrderEnumValues = []CustomContentSortOrder{
	"id",
	"-id",
	"created-date",
	"-created-date",
	"modified-date",
	"-modified-date",
	"title",
	"-title",
}

func (v *CustomContentSortOrder) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustomContentSortOrder(value)
	for _, existing := range AllowedCustomContentSortOrderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustomContentSortOrder", value)
}

// NewCustomContentSortOrderFromValue returns a pointer to a valid CustomContentSortOrder
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustomContentSortOrderFromValue(v string) (*CustomContentSortOrder, error) {
	ev := CustomContentSortOrder(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustomContentSortOrder: valid values are %v", v, AllowedCustomContentSortOrderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustomContentSortOrder) IsValid() bool {
	for _, existing := range AllowedCustomContentSortOrderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustomContentSortOrder value
func (v CustomContentSortOrder) Ptr() *CustomContentSortOrder {
	return &v
}

type NullableCustomContentSortOrder struct {
	value *CustomContentSortOrder
	isSet bool
}

func (v NullableCustomContentSortOrder) Get() *CustomContentSortOrder {
	return v.value
}

func (v *NullableCustomContentSortOrder) Set(val *CustomContentSortOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomContentSortOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomContentSortOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomContentSortOrder(val *CustomContentSortOrder) *NullableCustomContentSortOrder {
	return &NullableCustomContentSortOrder{value: val, isSet: true}
}

func (v NullableCustomContentSortOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomContentSortOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
