/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the SpaceSingleProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceSingleProperties{}

// SpaceSingleProperties struct for SpaceSingleProperties
type SpaceSingleProperties struct {
	Results []SpaceProperty `json:"results,omitempty"`
	Meta *OptionalFieldMeta `json:"meta,omitempty"`
	Links *OptionalFieldLinks `json:"_links,omitempty"`
}

// NewSpaceSingleProperties instantiates a new SpaceSingleProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceSingleProperties() *SpaceSingleProperties {
	this := SpaceSingleProperties{}
	return &this
}

// NewSpaceSinglePropertiesWithDefaults instantiates a new SpaceSingleProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceSinglePropertiesWithDefaults() *SpaceSingleProperties {
	this := SpaceSingleProperties{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *SpaceSingleProperties) GetResults() []SpaceProperty {
	if o == nil || IsNil(o.Results) {
		var ret []SpaceProperty
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceSingleProperties) GetResultsOk() ([]SpaceProperty, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *SpaceSingleProperties) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []SpaceProperty and assigns it to the Results field.
func (o *SpaceSingleProperties) SetResults(v []SpaceProperty) {
	o.Results = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SpaceSingleProperties) GetMeta() OptionalFieldMeta {
	if o == nil || IsNil(o.Meta) {
		var ret OptionalFieldMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceSingleProperties) GetMetaOk() (*OptionalFieldMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SpaceSingleProperties) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given OptionalFieldMeta and assigns it to the Meta field.
func (o *SpaceSingleProperties) SetMeta(v OptionalFieldMeta) {
	o.Meta = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *SpaceSingleProperties) GetLinks() OptionalFieldLinks {
	if o == nil || IsNil(o.Links) {
		var ret OptionalFieldLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpaceSingleProperties) GetLinksOk() (*OptionalFieldLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *SpaceSingleProperties) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given OptionalFieldLinks and assigns it to the Links field.
func (o *SpaceSingleProperties) SetLinks(v OptionalFieldLinks) {
	o.Links = &v
}

func (o SpaceSingleProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceSingleProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableSpaceSingleProperties struct {
	value *SpaceSingleProperties
	isSet bool
}

func (v NullableSpaceSingleProperties) Get() *SpaceSingleProperties {
	return v.value
}

func (v *NullableSpaceSingleProperties) Set(val *SpaceSingleProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceSingleProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceSingleProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceSingleProperties(val *SpaceSingleProperties) *NullableSpaceSingleProperties {
	return &NullableSpaceSingleProperties{value: val, isSet: true}
}

func (v NullableSpaceSingleProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceSingleProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


