/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the CreateSpaceRequestRoleAssignmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSpaceRequestRoleAssignmentsInner{}

// CreateSpaceRequestRoleAssignmentsInner The role assignments for the new space. If none are provided, the Default Space Roles are applied. If roles are provided, the space is created with exactly the provided set of roles. A private space is created if only the creator is assigned to a role and it’s the Admin role. At least one Admin role assignment must be specified.
type CreateSpaceRequestRoleAssignmentsInner struct {
	Principal *Principal `json:"principal,omitempty"`
	// The role to which the principal is assigned.
	RoleId *string `json:"roleId,omitempty"`
}

// NewCreateSpaceRequestRoleAssignmentsInner instantiates a new CreateSpaceRequestRoleAssignmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSpaceRequestRoleAssignmentsInner() *CreateSpaceRequestRoleAssignmentsInner {
	this := CreateSpaceRequestRoleAssignmentsInner{}
	return &this
}

// NewCreateSpaceRequestRoleAssignmentsInnerWithDefaults instantiates a new CreateSpaceRequestRoleAssignmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSpaceRequestRoleAssignmentsInnerWithDefaults() *CreateSpaceRequestRoleAssignmentsInner {
	this := CreateSpaceRequestRoleAssignmentsInner{}
	return &this
}

// GetPrincipal returns the Principal field value if set, zero value otherwise.
func (o *CreateSpaceRequestRoleAssignmentsInner) GetPrincipal() Principal {
	if o == nil || IsNil(o.Principal) {
		var ret Principal
		return ret
	}
	return *o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequestRoleAssignmentsInner) GetPrincipalOk() (*Principal, bool) {
	if o == nil || IsNil(o.Principal) {
		return nil, false
	}
	return o.Principal, true
}

// HasPrincipal returns a boolean if a field has been set.
func (o *CreateSpaceRequestRoleAssignmentsInner) HasPrincipal() bool {
	if o != nil && !IsNil(o.Principal) {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given Principal and assigns it to the Principal field.
func (o *CreateSpaceRequestRoleAssignmentsInner) SetPrincipal(v Principal) {
	o.Principal = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *CreateSpaceRequestRoleAssignmentsInner) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequestRoleAssignmentsInner) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *CreateSpaceRequestRoleAssignmentsInner) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *CreateSpaceRequestRoleAssignmentsInner) SetRoleId(v string) {
	o.RoleId = &v
}

func (o CreateSpaceRequestRoleAssignmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSpaceRequestRoleAssignmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Principal) {
		toSerialize["principal"] = o.Principal
	}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	return toSerialize, nil
}

type NullableCreateSpaceRequestRoleAssignmentsInner struct {
	value *CreateSpaceRequestRoleAssignmentsInner
	isSet bool
}

func (v NullableCreateSpaceRequestRoleAssignmentsInner) Get() *CreateSpaceRequestRoleAssignmentsInner {
	return v.value
}

func (v *NullableCreateSpaceRequestRoleAssignmentsInner) Set(val *CreateSpaceRequestRoleAssignmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSpaceRequestRoleAssignmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSpaceRequestRoleAssignmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSpaceRequestRoleAssignmentsInner(val *CreateSpaceRequestRoleAssignmentsInner) *NullableCreateSpaceRequestRoleAssignmentsInner {
	return &NullableCreateSpaceRequestRoleAssignmentsInner{value: val, isSet: true}
}

func (v NullableCreateSpaceRequestRoleAssignmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSpaceRequestRoleAssignmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


