/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePageRequest{}

// CreatePageRequest struct for CreatePageRequest
type CreatePageRequest struct {
	// ID of the space.
	SpaceId string `json:"spaceId"`
	// The status of the page, published or draft.
	Status *string `json:"status,omitempty"`
	// Title of the page, required if page status is not draft.
	Title *string `json:"title,omitempty"`
	// The parent content ID of the page. If the `root-level` query parameter is set to false and a value is  not supplied for this parameter, then the space homepage's ID will be used. If the `root-level` query  parameter is set to true, then a value may not be supplied for this parameter.
	ParentId *string `json:"parentId,omitempty"`
	Body *CreatePageRequestBody `json:"body,omitempty"`
	// The subtype of the page. Provide the subtype live to create a live doc or no subtype to create a page.
	Subtype *string `json:"subtype,omitempty"`
}

type _CreatePageRequest CreatePageRequest

// NewCreatePageRequest instantiates a new CreatePageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePageRequest(spaceId string) *CreatePageRequest {
	this := CreatePageRequest{}
	this.SpaceId = spaceId
	return &this
}

// NewCreatePageRequestWithDefaults instantiates a new CreatePageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePageRequestWithDefaults() *CreatePageRequest {
	this := CreatePageRequest{}
	return &this
}

// GetSpaceId returns the SpaceId field value
func (o *CreatePageRequest) GetSpaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value
// and a boolean to check if the value has been set.
func (o *CreatePageRequest) GetSpaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpaceId, true
}

// SetSpaceId sets field value
func (o *CreatePageRequest) SetSpaceId(v string) {
	o.SpaceId = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreatePageRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreatePageRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreatePageRequest) SetStatus(v string) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreatePageRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreatePageRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreatePageRequest) SetTitle(v string) {
	o.Title = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CreatePageRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageRequest) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CreatePageRequest) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *CreatePageRequest) SetParentId(v string) {
	o.ParentId = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CreatePageRequest) GetBody() CreatePageRequestBody {
	if o == nil || IsNil(o.Body) {
		var ret CreatePageRequestBody
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageRequest) GetBodyOk() (*CreatePageRequestBody, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CreatePageRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given CreatePageRequestBody and assigns it to the Body field.
func (o *CreatePageRequest) SetBody(v CreatePageRequestBody) {
	o.Body = &v
}

// GetSubtype returns the Subtype field value if set, zero value otherwise.
func (o *CreatePageRequest) GetSubtype() string {
	if o == nil || IsNil(o.Subtype) {
		var ret string
		return ret
	}
	return *o.Subtype
}

// GetSubtypeOk returns a tuple with the Subtype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePageRequest) GetSubtypeOk() (*string, bool) {
	if o == nil || IsNil(o.Subtype) {
		return nil, false
	}
	return o.Subtype, true
}

// HasSubtype returns a boolean if a field has been set.
func (o *CreatePageRequest) HasSubtype() bool {
	if o != nil && !IsNil(o.Subtype) {
		return true
	}

	return false
}

// SetSubtype gets a reference to the given string and assigns it to the Subtype field.
func (o *CreatePageRequest) SetSubtype(v string) {
	o.Subtype = &v
}

func (o CreatePageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spaceId"] = o.SpaceId
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Subtype) {
		toSerialize["subtype"] = o.Subtype
	}
	return toSerialize, nil
}

func (o *CreatePageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spaceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePageRequest := _CreatePageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePageRequest)

	if err != nil {
		return err
	}

	*o = CreatePageRequest(varCreatePageRequest)

	return err
}

type NullableCreatePageRequest struct {
	value *CreatePageRequest
	isSet bool
}

func (v NullableCreatePageRequest) Get() *CreatePageRequest {
	return v.value
}

func (v *NullableCreatePageRequest) Set(val *CreatePageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePageRequest(val *CreatePageRequest) *NullableCreatePageRequest {
	return &NullableCreatePageRequest{value: val, isSet: true}
}

func (v NullableCreatePageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


