/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"fmt"
)


// ConvertContentIdsToContentTypesRequestContentIdsInner struct for ConvertContentIdsToContentTypesRequestContentIdsInner
type ConvertContentIdsToContentTypesRequestContentIdsInner struct {
	Float32 *float32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ConvertContentIdsToContentTypesRequestContentIdsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32);
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ConvertContentIdsToContentTypesRequestContentIdsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConvertContentIdsToContentTypesRequestContentIdsInner) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableConvertContentIdsToContentTypesRequestContentIdsInner struct {
	value *ConvertContentIdsToContentTypesRequestContentIdsInner
	isSet bool
}

func (v NullableConvertContentIdsToContentTypesRequestContentIdsInner) Get() *ConvertContentIdsToContentTypesRequestContentIdsInner {
	return v.value
}

func (v *NullableConvertContentIdsToContentTypesRequestContentIdsInner) Set(val *ConvertContentIdsToContentTypesRequestContentIdsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConvertContentIdsToContentTypesRequestContentIdsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConvertContentIdsToContentTypesRequestContentIdsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConvertContentIdsToContentTypesRequestContentIdsInner(val *ConvertContentIdsToContentTypesRequestContentIdsInner) *NullableConvertContentIdsToContentTypesRequestContentIdsInner {
	return &NullableConvertContentIdsToContentTypesRequestContentIdsInner{value: val, isSet: true}
}

func (v NullableConvertContentIdsToContentTypesRequestContentIdsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConvertContentIdsToContentTypesRequestContentIdsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


