/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the OptionalFieldLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OptionalFieldLinks{}

// OptionalFieldLinks struct for OptionalFieldLinks
type OptionalFieldLinks struct {
	// A relative URL that can be used to fetch results beyond what this include parameter retrieves.
	Self *string `json:"self,omitempty"`
}

// NewOptionalFieldLinks instantiates a new OptionalFieldLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOptionalFieldLinks() *OptionalFieldLinks {
	this := OptionalFieldLinks{}
	return &this
}

// NewOptionalFieldLinksWithDefaults instantiates a new OptionalFieldLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionalFieldLinksWithDefaults() *OptionalFieldLinks {
	this := OptionalFieldLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *OptionalFieldLinks) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionalFieldLinks) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *OptionalFieldLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *OptionalFieldLinks) SetSelf(v string) {
	o.Self = &v
}

func (o OptionalFieldLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OptionalFieldLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableOptionalFieldLinks struct {
	value *OptionalFieldLinks
	isSet bool
}

func (v NullableOptionalFieldLinks) Get() *OptionalFieldLinks {
	return v.value
}

func (v *NullableOptionalFieldLinks) Set(val *OptionalFieldLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableOptionalFieldLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableOptionalFieldLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptionalFieldLinks(val *OptionalFieldLinks) *NullableOptionalFieldLinks {
	return &NullableOptionalFieldLinks{value: val, isSet: true}
}

func (v NullableOptionalFieldLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptionalFieldLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


