/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the AttachmentCommentModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachmentCommentModel{}

// AttachmentCommentModel struct for AttachmentCommentModel
type AttachmentCommentModel struct {
	// ID of the comment.
	Id *string `json:"id,omitempty"`
	Status *ContentStatus `json:"status,omitempty"`
	// Title of the comment.
	Title *string `json:"title,omitempty"`
	// ID of the attachment containing the comment.
	AttachmentId *string `json:"attachmentId,omitempty"`
	Version *Version `json:"version,omitempty"`
	Body *BodySingle `json:"body,omitempty"`
	Links *CommentLinks `json:"_links,omitempty"`
}

// NewAttachmentCommentModel instantiates a new AttachmentCommentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentCommentModel() *AttachmentCommentModel {
	this := AttachmentCommentModel{}
	return &this
}

// NewAttachmentCommentModelWithDefaults instantiates a new AttachmentCommentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentCommentModelWithDefaults() *AttachmentCommentModel {
	this := AttachmentCommentModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AttachmentCommentModel) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetStatus() ContentStatus {
	if o == nil || IsNil(o.Status) {
		var ret ContentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetStatusOk() (*ContentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ContentStatus and assigns it to the Status field.
func (o *AttachmentCommentModel) SetStatus(v ContentStatus) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AttachmentCommentModel) SetTitle(v string) {
	o.Title = &v
}

// GetAttachmentId returns the AttachmentId field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetAttachmentId() string {
	if o == nil || IsNil(o.AttachmentId) {
		var ret string
		return ret
	}
	return *o.AttachmentId
}

// GetAttachmentIdOk returns a tuple with the AttachmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetAttachmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AttachmentId) {
		return nil, false
	}
	return o.AttachmentId, true
}

// HasAttachmentId returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasAttachmentId() bool {
	if o != nil && !IsNil(o.AttachmentId) {
		return true
	}

	return false
}

// SetAttachmentId gets a reference to the given string and assigns it to the AttachmentId field.
func (o *AttachmentCommentModel) SetAttachmentId(v string) {
	o.AttachmentId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetVersion() Version {
	if o == nil || IsNil(o.Version) {
		var ret Version
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetVersionOk() (*Version, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given Version and assigns it to the Version field.
func (o *AttachmentCommentModel) SetVersion(v Version) {
	o.Version = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetBody() BodySingle {
	if o == nil || IsNil(o.Body) {
		var ret BodySingle
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetBodyOk() (*BodySingle, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given BodySingle and assigns it to the Body field.
func (o *AttachmentCommentModel) SetBody(v BodySingle) {
	o.Body = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AttachmentCommentModel) GetLinks() CommentLinks {
	if o == nil || IsNil(o.Links) {
		var ret CommentLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentCommentModel) GetLinksOk() (*CommentLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AttachmentCommentModel) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CommentLinks and assigns it to the Links field.
func (o *AttachmentCommentModel) SetLinks(v CommentLinks) {
	o.Links = &v
}

func (o AttachmentCommentModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachmentCommentModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.AttachmentId) {
		toSerialize["attachmentId"] = o.AttachmentId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableAttachmentCommentModel struct {
	value *AttachmentCommentModel
	isSet bool
}

func (v NullableAttachmentCommentModel) Get() *AttachmentCommentModel {
	return v.value
}

func (v *NullableAttachmentCommentModel) Set(val *AttachmentCommentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentCommentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentCommentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentCommentModel(val *AttachmentCommentModel) *NullableAttachmentCommentModel {
	return &NullableAttachmentCommentModel{value: val, isSet: true}
}

func (v NullableAttachmentCommentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentCommentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


