/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSpaceRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSpaceRoleRequest{}

// CreateSpaceRoleRequest struct for CreateSpaceRoleRequest
type CreateSpaceRoleRequest struct {
	// Name of the space role
	Name string `json:"name"`
	// Description for the space role
	Description string `json:"description"`
	// The ids of the space permissions associated with the space role. Sample value \"read/space\"; retrieve ids from responses returned by [GET /space-permissions](https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-space-permissions/#api-space-permissions-get) endpoint
	SpacePermissions []string `json:"spacePermissions"`
}

type _CreateSpaceRoleRequest CreateSpaceRoleRequest

// NewCreateSpaceRoleRequest instantiates a new CreateSpaceRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSpaceRoleRequest(name string, description string, spacePermissions []string) *CreateSpaceRoleRequest {
	this := CreateSpaceRoleRequest{}
	this.Name = name
	this.Description = description
	this.SpacePermissions = spacePermissions
	return &this
}

// NewCreateSpaceRoleRequestWithDefaults instantiates a new CreateSpaceRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSpaceRoleRequestWithDefaults() *CreateSpaceRoleRequest {
	this := CreateSpaceRoleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSpaceRoleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSpaceRoleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSpaceRoleRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreateSpaceRoleRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateSpaceRoleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateSpaceRoleRequest) SetDescription(v string) {
	o.Description = v
}

// GetSpacePermissions returns the SpacePermissions field value
func (o *CreateSpaceRoleRequest) GetSpacePermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SpacePermissions
}

// GetSpacePermissionsOk returns a tuple with the SpacePermissions field value
// and a boolean to check if the value has been set.
func (o *CreateSpaceRoleRequest) GetSpacePermissionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpacePermissions, true
}

// SetSpacePermissions sets field value
func (o *CreateSpaceRoleRequest) SetSpacePermissions(v []string) {
	o.SpacePermissions = v
}

func (o CreateSpaceRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSpaceRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["spacePermissions"] = o.SpacePermissions
	return toSerialize, nil
}

func (o *CreateSpaceRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"spacePermissions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSpaceRoleRequest := _CreateSpaceRoleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSpaceRoleRequest)

	if err != nil {
		return err
	}

	*o = CreateSpaceRoleRequest(varCreateSpaceRoleRequest)

	return err
}

type NullableCreateSpaceRoleRequest struct {
	value *CreateSpaceRoleRequest
	isSet bool
}

func (v NullableCreateSpaceRoleRequest) Get() *CreateSpaceRoleRequest {
	return v.value
}

func (v *NullableCreateSpaceRoleRequest) Set(val *CreateSpaceRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSpaceRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSpaceRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSpaceRoleRequest(val *CreateSpaceRoleRequest) *NullableCreateSpaceRoleRequest {
	return &NullableCreateSpaceRoleRequest{value: val, isSet: true}
}

func (v NullableCreateSpaceRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSpaceRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


