/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSpaceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSpaceRequest{}

// CreateSpaceRequest struct for CreateSpaceRequest
type CreateSpaceRequest struct {
	// The name of the space to be created.
	Name string `json:"name"`
	// The key for the new space. See [Space Keys](https://support.atlassian.com/confluence-cloud/docs/create-a-space/). If the key property is not provided, the alias property is required to be used instead.
	Key *string `json:"key,omitempty"`
	// This field will be used as the new identifier for the space in confluence page URLs. If the alias property is not provided, the key property is required to be used instead. Maximum 255 alphanumeric characters in length.
	Alias *string `json:"alias,omitempty"`
	Description *CreateSpaceRequestDescription `json:"description,omitempty"`
	RoleAssignments []CreateSpaceRequestRoleAssignmentsInner `json:"roleAssignments,omitempty"`
	// The id of the space to copy the space access configuration from.
	CopySpaceAccessConfiguration *int32 `json:"copySpaceAccessConfiguration,omitempty"`
	// Whether to create the space as private.
	CreatePrivateSpace *bool `json:"createPrivateSpace,omitempty"`
	// The key of the template to use.
	TemplateKey *string `json:"templateKey,omitempty"`
}

type _CreateSpaceRequest CreateSpaceRequest

// NewCreateSpaceRequest instantiates a new CreateSpaceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSpaceRequest(name string) *CreateSpaceRequest {
	this := CreateSpaceRequest{}
	this.Name = name
	return &this
}

// NewCreateSpaceRequestWithDefaults instantiates a new CreateSpaceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSpaceRequestWithDefaults() *CreateSpaceRequest {
	this := CreateSpaceRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSpaceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSpaceRequest) SetName(v string) {
	o.Name = v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CreateSpaceRequest) SetKey(v string) {
	o.Key = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *CreateSpaceRequest) SetAlias(v string) {
	o.Alias = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetDescription() CreateSpaceRequestDescription {
	if o == nil || IsNil(o.Description) {
		var ret CreateSpaceRequestDescription
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetDescriptionOk() (*CreateSpaceRequestDescription, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given CreateSpaceRequestDescription and assigns it to the Description field.
func (o *CreateSpaceRequest) SetDescription(v CreateSpaceRequestDescription) {
	o.Description = &v
}

// GetRoleAssignments returns the RoleAssignments field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetRoleAssignments() []CreateSpaceRequestRoleAssignmentsInner {
	if o == nil || IsNil(o.RoleAssignments) {
		var ret []CreateSpaceRequestRoleAssignmentsInner
		return ret
	}
	return o.RoleAssignments
}

// GetRoleAssignmentsOk returns a tuple with the RoleAssignments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetRoleAssignmentsOk() ([]CreateSpaceRequestRoleAssignmentsInner, bool) {
	if o == nil || IsNil(o.RoleAssignments) {
		return nil, false
	}
	return o.RoleAssignments, true
}

// HasRoleAssignments returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasRoleAssignments() bool {
	if o != nil && !IsNil(o.RoleAssignments) {
		return true
	}

	return false
}

// SetRoleAssignments gets a reference to the given []CreateSpaceRequestRoleAssignmentsInner and assigns it to the RoleAssignments field.
func (o *CreateSpaceRequest) SetRoleAssignments(v []CreateSpaceRequestRoleAssignmentsInner) {
	o.RoleAssignments = v
}

// GetCopySpaceAccessConfiguration returns the CopySpaceAccessConfiguration field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetCopySpaceAccessConfiguration() int32 {
	if o == nil || IsNil(o.CopySpaceAccessConfiguration) {
		var ret int32
		return ret
	}
	return *o.CopySpaceAccessConfiguration
}

// GetCopySpaceAccessConfigurationOk returns a tuple with the CopySpaceAccessConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetCopySpaceAccessConfigurationOk() (*int32, bool) {
	if o == nil || IsNil(o.CopySpaceAccessConfiguration) {
		return nil, false
	}
	return o.CopySpaceAccessConfiguration, true
}

// HasCopySpaceAccessConfiguration returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasCopySpaceAccessConfiguration() bool {
	if o != nil && !IsNil(o.CopySpaceAccessConfiguration) {
		return true
	}

	return false
}

// SetCopySpaceAccessConfiguration gets a reference to the given int32 and assigns it to the CopySpaceAccessConfiguration field.
func (o *CreateSpaceRequest) SetCopySpaceAccessConfiguration(v int32) {
	o.CopySpaceAccessConfiguration = &v
}

// GetCreatePrivateSpace returns the CreatePrivateSpace field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetCreatePrivateSpace() bool {
	if o == nil || IsNil(o.CreatePrivateSpace) {
		var ret bool
		return ret
	}
	return *o.CreatePrivateSpace
}

// GetCreatePrivateSpaceOk returns a tuple with the CreatePrivateSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetCreatePrivateSpaceOk() (*bool, bool) {
	if o == nil || IsNil(o.CreatePrivateSpace) {
		return nil, false
	}
	return o.CreatePrivateSpace, true
}

// HasCreatePrivateSpace returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasCreatePrivateSpace() bool {
	if o != nil && !IsNil(o.CreatePrivateSpace) {
		return true
	}

	return false
}

// SetCreatePrivateSpace gets a reference to the given bool and assigns it to the CreatePrivateSpace field.
func (o *CreateSpaceRequest) SetCreatePrivateSpace(v bool) {
	o.CreatePrivateSpace = &v
}

// GetTemplateKey returns the TemplateKey field value if set, zero value otherwise.
func (o *CreateSpaceRequest) GetTemplateKey() string {
	if o == nil || IsNil(o.TemplateKey) {
		var ret string
		return ret
	}
	return *o.TemplateKey
}

// GetTemplateKeyOk returns a tuple with the TemplateKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpaceRequest) GetTemplateKeyOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateKey) {
		return nil, false
	}
	return o.TemplateKey, true
}

// HasTemplateKey returns a boolean if a field has been set.
func (o *CreateSpaceRequest) HasTemplateKey() bool {
	if o != nil && !IsNil(o.TemplateKey) {
		return true
	}

	return false
}

// SetTemplateKey gets a reference to the given string and assigns it to the TemplateKey field.
func (o *CreateSpaceRequest) SetTemplateKey(v string) {
	o.TemplateKey = &v
}

func (o CreateSpaceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSpaceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RoleAssignments) {
		toSerialize["roleAssignments"] = o.RoleAssignments
	}
	if !IsNil(o.CopySpaceAccessConfiguration) {
		toSerialize["copySpaceAccessConfiguration"] = o.CopySpaceAccessConfiguration
	}
	if !IsNil(o.CreatePrivateSpace) {
		toSerialize["createPrivateSpace"] = o.CreatePrivateSpace
	}
	if !IsNil(o.TemplateKey) {
		toSerialize["templateKey"] = o.TemplateKey
	}
	return toSerialize, nil
}

func (o *CreateSpaceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSpaceRequest := _CreateSpaceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSpaceRequest)

	if err != nil {
		return err
	}

	*o = CreateSpaceRequest(varCreateSpaceRequest)

	return err
}

type NullableCreateSpaceRequest struct {
	value *CreateSpaceRequest
	isSet bool
}

func (v NullableCreateSpaceRequest) Get() *CreateSpaceRequest {
	return v.value
}

func (v *NullableCreateSpaceRequest) Set(val *CreateSpaceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSpaceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSpaceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSpaceRequest(val *CreateSpaceRequest) *NullableCreateSpaceRequest {
	return &NullableCreateSpaceRequest{value: val, isSet: true}
}

func (v NullableCreateSpaceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSpaceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


