/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateBlogPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBlogPostRequest{}

// UpdateBlogPostRequest struct for UpdateBlogPostRequest
type UpdateBlogPostRequest struct {
	// Id of the blog post.
	Id string `json:"id"`
	// The updated status of the blog post.  Note, if you change the status of a blog post from 'current' to 'draft' and it has an existing draft, the existing draft will be deleted in favor of the updated draft. Additionally, this endpoint can be used to restore a 'trashed' or 'deleted' blog post to 'current' status. For restoration, blog post contents will not be updated and only the blog post status will be changed.
	Status string `json:"status"`
	// Title of the blog post.
	Title string `json:"title"`
	// ID of the containing space.  This currently **does not support moving the blog post to a different space**.
	SpaceId *string `json:"spaceId,omitempty"`
	Body CreateBlogPostRequestBody `json:"body"`
	Version UpdateBlogPostRequestVersion `json:"version"`
	// Created date of the blog post in the format of \"yyyy-MM-ddTHH:mm:ss.SSSZ\".
	CreatedAt *string `json:"createdAt,omitempty"`
}

type _UpdateBlogPostRequest UpdateBlogPostRequest

// NewUpdateBlogPostRequest instantiates a new UpdateBlogPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBlogPostRequest(id string, status string, title string, body CreateBlogPostRequestBody, version UpdateBlogPostRequestVersion) *UpdateBlogPostRequest {
	this := UpdateBlogPostRequest{}
	this.Id = id
	this.Status = status
	this.Title = title
	this.Body = body
	this.Version = version
	return &this
}

// NewUpdateBlogPostRequestWithDefaults instantiates a new UpdateBlogPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBlogPostRequestWithDefaults() *UpdateBlogPostRequest {
	this := UpdateBlogPostRequest{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateBlogPostRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateBlogPostRequest) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *UpdateBlogPostRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateBlogPostRequest) SetStatus(v string) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *UpdateBlogPostRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UpdateBlogPostRequest) SetTitle(v string) {
	o.Title = v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *UpdateBlogPostRequest) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *UpdateBlogPostRequest) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *UpdateBlogPostRequest) SetSpaceId(v string) {
	o.SpaceId = &v
}

// GetBody returns the Body field value
func (o *UpdateBlogPostRequest) GetBody() CreateBlogPostRequestBody {
	if o == nil {
		var ret CreateBlogPostRequestBody
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetBodyOk() (*CreateBlogPostRequestBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *UpdateBlogPostRequest) SetBody(v CreateBlogPostRequestBody) {
	o.Body = v
}

// GetVersion returns the Version field value
func (o *UpdateBlogPostRequest) GetVersion() UpdateBlogPostRequestVersion {
	if o == nil {
		var ret UpdateBlogPostRequestVersion
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetVersionOk() (*UpdateBlogPostRequestVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *UpdateBlogPostRequest) SetVersion(v UpdateBlogPostRequestVersion) {
	o.Version = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UpdateBlogPostRequest) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlogPostRequest) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UpdateBlogPostRequest) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *UpdateBlogPostRequest) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o UpdateBlogPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBlogPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	if !IsNil(o.SpaceId) {
		toSerialize["spaceId"] = o.SpaceId
	}
	toSerialize["body"] = o.Body
	toSerialize["version"] = o.Version
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

func (o *UpdateBlogPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"title",
		"body",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateBlogPostRequest := _UpdateBlogPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateBlogPostRequest)

	if err != nil {
		return err
	}

	*o = UpdateBlogPostRequest(varUpdateBlogPostRequest)

	return err
}

type NullableUpdateBlogPostRequest struct {
	value *UpdateBlogPostRequest
	isSet bool
}

func (v NullableUpdateBlogPostRequest) Get() *UpdateBlogPostRequest {
	return v.value
}

func (v *NullableUpdateBlogPostRequest) Set(val *UpdateBlogPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBlogPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBlogPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBlogPostRequest(val *UpdateBlogPostRequest) *NullableUpdateBlogPostRequest {
	return &NullableUpdateBlogPostRequest{value: val, isSet: true}
}

func (v NullableUpdateBlogPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBlogPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


