/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"time"
)

// checks if the CreateSpace201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSpace201Response{}

// CreateSpace201Response struct for CreateSpace201Response
type CreateSpace201Response struct {
	// ID of the space.
	Id *string `json:"id,omitempty"`
	// Key of the space.
	Key *string `json:"key,omitempty"`
	// Name of the space.
	Name *string `json:"name,omitempty"`
	Type *SpaceType `json:"type,omitempty"`
	Status *SpaceStatus `json:"status,omitempty"`
	// The account ID of the user who created this space originally.
	AuthorId *string `json:"authorId,omitempty"`
	// Currently active alias for a Confluence space.
	CurrentActiveAlias *string `json:"currentActiveAlias,omitempty"`
	// Date and time when the space was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// ID of the space's homepage.
	HomepageId *string `json:"homepageId,omitempty"`
	Description *SpaceDescription `json:"description,omitempty"`
	Icon *SpaceIcon `json:"icon,omitempty"`
	Links *GetAttachmentById200ResponseAllOfLinks `json:"_links,omitempty"`
}

// NewCreateSpace201Response instantiates a new CreateSpace201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSpace201Response() *CreateSpace201Response {
	this := CreateSpace201Response{}
	return &this
}

// NewCreateSpace201ResponseWithDefaults instantiates a new CreateSpace201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSpace201ResponseWithDefaults() *CreateSpace201Response {
	this := CreateSpace201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateSpace201Response) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CreateSpace201Response) SetKey(v string) {
	o.Key = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateSpace201Response) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetType() SpaceType {
	if o == nil || IsNil(o.Type) {
		var ret SpaceType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetTypeOk() (*SpaceType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given SpaceType and assigns it to the Type field.
func (o *CreateSpace201Response) SetType(v SpaceType) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetStatus() SpaceStatus {
	if o == nil || IsNil(o.Status) {
		var ret SpaceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetStatusOk() (*SpaceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given SpaceStatus and assigns it to the Status field.
func (o *CreateSpace201Response) SetStatus(v SpaceStatus) {
	o.Status = &v
}

// GetAuthorId returns the AuthorId field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetAuthorId() string {
	if o == nil || IsNil(o.AuthorId) {
		var ret string
		return ret
	}
	return *o.AuthorId
}

// GetAuthorIdOk returns a tuple with the AuthorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetAuthorIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorId) {
		return nil, false
	}
	return o.AuthorId, true
}

// HasAuthorId returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasAuthorId() bool {
	if o != nil && !IsNil(o.AuthorId) {
		return true
	}

	return false
}

// SetAuthorId gets a reference to the given string and assigns it to the AuthorId field.
func (o *CreateSpace201Response) SetAuthorId(v string) {
	o.AuthorId = &v
}

// GetCurrentActiveAlias returns the CurrentActiveAlias field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetCurrentActiveAlias() string {
	if o == nil || IsNil(o.CurrentActiveAlias) {
		var ret string
		return ret
	}
	return *o.CurrentActiveAlias
}

// GetCurrentActiveAliasOk returns a tuple with the CurrentActiveAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetCurrentActiveAliasOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentActiveAlias) {
		return nil, false
	}
	return o.CurrentActiveAlias, true
}

// HasCurrentActiveAlias returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasCurrentActiveAlias() bool {
	if o != nil && !IsNil(o.CurrentActiveAlias) {
		return true
	}

	return false
}

// SetCurrentActiveAlias gets a reference to the given string and assigns it to the CurrentActiveAlias field.
func (o *CreateSpace201Response) SetCurrentActiveAlias(v string) {
	o.CurrentActiveAlias = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CreateSpace201Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetHomepageId returns the HomepageId field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetHomepageId() string {
	if o == nil || IsNil(o.HomepageId) {
		var ret string
		return ret
	}
	return *o.HomepageId
}

// GetHomepageIdOk returns a tuple with the HomepageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetHomepageIdOk() (*string, bool) {
	if o == nil || IsNil(o.HomepageId) {
		return nil, false
	}
	return o.HomepageId, true
}

// HasHomepageId returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasHomepageId() bool {
	if o != nil && !IsNil(o.HomepageId) {
		return true
	}

	return false
}

// SetHomepageId gets a reference to the given string and assigns it to the HomepageId field.
func (o *CreateSpace201Response) SetHomepageId(v string) {
	o.HomepageId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetDescription() SpaceDescription {
	if o == nil || IsNil(o.Description) {
		var ret SpaceDescription
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetDescriptionOk() (*SpaceDescription, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given SpaceDescription and assigns it to the Description field.
func (o *CreateSpace201Response) SetDescription(v SpaceDescription) {
	o.Description = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetIcon() SpaceIcon {
	if o == nil || IsNil(o.Icon) {
		var ret SpaceIcon
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetIconOk() (*SpaceIcon, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given SpaceIcon and assigns it to the Icon field.
func (o *CreateSpace201Response) SetIcon(v SpaceIcon) {
	o.Icon = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CreateSpace201Response) GetLinks() GetAttachmentById200ResponseAllOfLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetAttachmentById200ResponseAllOfLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSpace201Response) GetLinksOk() (*GetAttachmentById200ResponseAllOfLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CreateSpace201Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetAttachmentById200ResponseAllOfLinks and assigns it to the Links field.
func (o *CreateSpace201Response) SetLinks(v GetAttachmentById200ResponseAllOfLinks) {
	o.Links = &v
}

func (o CreateSpace201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSpace201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.AuthorId) {
		toSerialize["authorId"] = o.AuthorId
	}
	if !IsNil(o.CurrentActiveAlias) {
		toSerialize["currentActiveAlias"] = o.CurrentActiveAlias
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.HomepageId) {
		toSerialize["homepageId"] = o.HomepageId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCreateSpace201Response struct {
	value *CreateSpace201Response
	isSet bool
}

func (v NullableCreateSpace201Response) Get() *CreateSpace201Response {
	return v.value
}

func (v *NullableCreateSpace201Response) Set(val *CreateSpace201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSpace201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSpace201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSpace201Response(val *CreateSpace201Response) *NullableCreateSpace201Response {
	return &NullableCreateSpace201Response{value: val, isSet: true}
}

func (v NullableCreateSpace201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSpace201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


