/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the DataPolicySpaceDataPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataPolicySpaceDataPolicy{}

// DataPolicySpaceDataPolicy struct for DataPolicySpaceDataPolicy
type DataPolicySpaceDataPolicy struct {
	// Whether the space contains any content blocked for (inaccessible to) the requesting client application.
	AnyContentBlocked *bool `json:"anyContentBlocked,omitempty"`
}

// NewDataPolicySpaceDataPolicy instantiates a new DataPolicySpaceDataPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPolicySpaceDataPolicy() *DataPolicySpaceDataPolicy {
	this := DataPolicySpaceDataPolicy{}
	return &this
}

// NewDataPolicySpaceDataPolicyWithDefaults instantiates a new DataPolicySpaceDataPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPolicySpaceDataPolicyWithDefaults() *DataPolicySpaceDataPolicy {
	this := DataPolicySpaceDataPolicy{}
	return &this
}

// GetAnyContentBlocked returns the AnyContentBlocked field value if set, zero value otherwise.
func (o *DataPolicySpaceDataPolicy) GetAnyContentBlocked() bool {
	if o == nil || IsNil(o.AnyContentBlocked) {
		var ret bool
		return ret
	}
	return *o.AnyContentBlocked
}

// GetAnyContentBlockedOk returns a tuple with the AnyContentBlocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPolicySpaceDataPolicy) GetAnyContentBlockedOk() (*bool, bool) {
	if o == nil || IsNil(o.AnyContentBlocked) {
		return nil, false
	}
	return o.AnyContentBlocked, true
}

// HasAnyContentBlocked returns a boolean if a field has been set.
func (o *DataPolicySpaceDataPolicy) HasAnyContentBlocked() bool {
	if o != nil && !IsNil(o.AnyContentBlocked) {
		return true
	}

	return false
}

// SetAnyContentBlocked gets a reference to the given bool and assigns it to the AnyContentBlocked field.
func (o *DataPolicySpaceDataPolicy) SetAnyContentBlocked(v bool) {
	o.AnyContentBlocked = &v
}

func (o DataPolicySpaceDataPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataPolicySpaceDataPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnyContentBlocked) {
		toSerialize["anyContentBlocked"] = o.AnyContentBlocked
	}
	return toSerialize, nil
}

type NullableDataPolicySpaceDataPolicy struct {
	value *DataPolicySpaceDataPolicy
	isSet bool
}

func (v NullableDataPolicySpaceDataPolicy) Get() *DataPolicySpaceDataPolicy {
	return v.value
}

func (v *NullableDataPolicySpaceDataPolicy) Set(val *DataPolicySpaceDataPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPolicySpaceDataPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPolicySpaceDataPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPolicySpaceDataPolicy(val *DataPolicySpaceDataPolicy) *NullableDataPolicySpaceDataPolicy {
	return &NullableDataPolicySpaceDataPolicy{value: val, isSet: true}
}

func (v NullableDataPolicySpaceDataPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPolicySpaceDataPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


