/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the SpacePermission type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpacePermission{}

// SpacePermission struct for SpacePermission
type SpacePermission struct {
	// The identifier for the space permission.
	Id *string `json:"id,omitempty"`
	// The display name for the space permission.
	DisplayName *string `json:"displayName,omitempty"`
	// Describes the space permission’s usage.
	Description *string `json:"description,omitempty"`
	// The permissions required for this permission to be enabled.
	RequiredPermissionIds []string `json:"requiredPermissionIds,omitempty"`
}

// NewSpacePermission instantiates a new SpacePermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpacePermission() *SpacePermission {
	this := SpacePermission{}
	return &this
}

// NewSpacePermissionWithDefaults instantiates a new SpacePermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpacePermissionWithDefaults() *SpacePermission {
	this := SpacePermission{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SpacePermission) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermission) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SpacePermission) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SpacePermission) SetId(v string) {
	o.Id = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *SpacePermission) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermission) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *SpacePermission) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *SpacePermission) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SpacePermission) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermission) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SpacePermission) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SpacePermission) SetDescription(v string) {
	o.Description = &v
}

// GetRequiredPermissionIds returns the RequiredPermissionIds field value if set, zero value otherwise.
func (o *SpacePermission) GetRequiredPermissionIds() []string {
	if o == nil || IsNil(o.RequiredPermissionIds) {
		var ret []string
		return ret
	}
	return o.RequiredPermissionIds
}

// GetRequiredPermissionIdsOk returns a tuple with the RequiredPermissionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpacePermission) GetRequiredPermissionIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredPermissionIds) {
		return nil, false
	}
	return o.RequiredPermissionIds, true
}

// HasRequiredPermissionIds returns a boolean if a field has been set.
func (o *SpacePermission) HasRequiredPermissionIds() bool {
	if o != nil && !IsNil(o.RequiredPermissionIds) {
		return true
	}

	return false
}

// SetRequiredPermissionIds gets a reference to the given []string and assigns it to the RequiredPermissionIds field.
func (o *SpacePermission) SetRequiredPermissionIds(v []string) {
	o.RequiredPermissionIds = v
}

func (o SpacePermission) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpacePermission) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RequiredPermissionIds) {
		toSerialize["requiredPermissionIds"] = o.RequiredPermissionIds
	}
	return toSerialize, nil
}

type NullableSpacePermission struct {
	value *SpacePermission
	isSet bool
}

func (v NullableSpacePermission) Get() *SpacePermission {
	return v.value
}

func (v *NullableSpacePermission) Set(val *SpacePermission) {
	v.value = val
	v.isSet = true
}

func (v NullableSpacePermission) IsSet() bool {
	return v.isSet
}

func (v *NullableSpacePermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpacePermission(val *SpacePermission) *NullableSpacePermission {
	return &NullableSpacePermission{value: val, isSet: true}
}

func (v NullableSpacePermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpacePermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


