/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"time"
)

// checks if the InlineCommentModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineCommentModel{}

// InlineCommentModel struct for InlineCommentModel
type InlineCommentModel struct {
	// ID of the comment.
	Id *string `json:"id,omitempty"`
	Status *ContentStatus `json:"status,omitempty"`
	// Title of the comment.
	Title *string `json:"title,omitempty"`
	// ID of the blog post containing the comment if the comment is on a blog post.
	BlogPostId *string `json:"blogPostId,omitempty"`
	// ID of the page containing the comment if the comment is on a page.
	PageId *string `json:"pageId,omitempty"`
	// ID of the parent comment if the comment is a reply.
	ParentCommentId *string `json:"parentCommentId,omitempty"`
	Version *Version `json:"version,omitempty"`
	Body *BodySingle `json:"body,omitempty"`
	// Atlassian Account ID of last person who modified the resolve state of the comment. Null until comment is resolved or reopened.
	ResolutionLastModifierId *string `json:"resolutionLastModifierId,omitempty"`
	// Timestamp of the last modification to the comment's resolution status. Null until comment is resolved or reopened.
	ResolutionLastModifiedAt *time.Time `json:"resolutionLastModifiedAt,omitempty"`
	ResolutionStatus *InlineCommentResolutionStatus `json:"resolutionStatus,omitempty"`
	Properties *InlineCommentModelProperties `json:"properties,omitempty"`
	Operations *AttachmentSingleOperations `json:"operations,omitempty"`
	Likes *BlogPostSingleLikes `json:"likes,omitempty"`
	Versions *AttachmentSingleVersions `json:"versions,omitempty"`
	Links *CommentLinks `json:"_links,omitempty"`
}

// NewInlineCommentModel instantiates a new InlineCommentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineCommentModel() *InlineCommentModel {
	this := InlineCommentModel{}
	return &this
}

// NewInlineCommentModelWithDefaults instantiates a new InlineCommentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineCommentModelWithDefaults() *InlineCommentModel {
	this := InlineCommentModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineCommentModel) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineCommentModel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InlineCommentModel) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InlineCommentModel) GetStatus() ContentStatus {
	if o == nil || IsNil(o.Status) {
		var ret ContentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetStatusOk() (*ContentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InlineCommentModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ContentStatus and assigns it to the Status field.
func (o *InlineCommentModel) SetStatus(v ContentStatus) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *InlineCommentModel) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *InlineCommentModel) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *InlineCommentModel) SetTitle(v string) {
	o.Title = &v
}

// GetBlogPostId returns the BlogPostId field value if set, zero value otherwise.
func (o *InlineCommentModel) GetBlogPostId() string {
	if o == nil || IsNil(o.BlogPostId) {
		var ret string
		return ret
	}
	return *o.BlogPostId
}

// GetBlogPostIdOk returns a tuple with the BlogPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetBlogPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlogPostId) {
		return nil, false
	}
	return o.BlogPostId, true
}

// HasBlogPostId returns a boolean if a field has been set.
func (o *InlineCommentModel) HasBlogPostId() bool {
	if o != nil && !IsNil(o.BlogPostId) {
		return true
	}

	return false
}

// SetBlogPostId gets a reference to the given string and assigns it to the BlogPostId field.
func (o *InlineCommentModel) SetBlogPostId(v string) {
	o.BlogPostId = &v
}

// GetPageId returns the PageId field value if set, zero value otherwise.
func (o *InlineCommentModel) GetPageId() string {
	if o == nil || IsNil(o.PageId) {
		var ret string
		return ret
	}
	return *o.PageId
}

// GetPageIdOk returns a tuple with the PageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetPageIdOk() (*string, bool) {
	if o == nil || IsNil(o.PageId) {
		return nil, false
	}
	return o.PageId, true
}

// HasPageId returns a boolean if a field has been set.
func (o *InlineCommentModel) HasPageId() bool {
	if o != nil && !IsNil(o.PageId) {
		return true
	}

	return false
}

// SetPageId gets a reference to the given string and assigns it to the PageId field.
func (o *InlineCommentModel) SetPageId(v string) {
	o.PageId = &v
}

// GetParentCommentId returns the ParentCommentId field value if set, zero value otherwise.
func (o *InlineCommentModel) GetParentCommentId() string {
	if o == nil || IsNil(o.ParentCommentId) {
		var ret string
		return ret
	}
	return *o.ParentCommentId
}

// GetParentCommentIdOk returns a tuple with the ParentCommentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetParentCommentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentCommentId) {
		return nil, false
	}
	return o.ParentCommentId, true
}

// HasParentCommentId returns a boolean if a field has been set.
func (o *InlineCommentModel) HasParentCommentId() bool {
	if o != nil && !IsNil(o.ParentCommentId) {
		return true
	}

	return false
}

// SetParentCommentId gets a reference to the given string and assigns it to the ParentCommentId field.
func (o *InlineCommentModel) SetParentCommentId(v string) {
	o.ParentCommentId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *InlineCommentModel) GetVersion() Version {
	if o == nil || IsNil(o.Version) {
		var ret Version
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetVersionOk() (*Version, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *InlineCommentModel) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given Version and assigns it to the Version field.
func (o *InlineCommentModel) SetVersion(v Version) {
	o.Version = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *InlineCommentModel) GetBody() BodySingle {
	if o == nil || IsNil(o.Body) {
		var ret BodySingle
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetBodyOk() (*BodySingle, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *InlineCommentModel) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given BodySingle and assigns it to the Body field.
func (o *InlineCommentModel) SetBody(v BodySingle) {
	o.Body = &v
}

// GetResolutionLastModifierId returns the ResolutionLastModifierId field value if set, zero value otherwise.
func (o *InlineCommentModel) GetResolutionLastModifierId() string {
	if o == nil || IsNil(o.ResolutionLastModifierId) {
		var ret string
		return ret
	}
	return *o.ResolutionLastModifierId
}

// GetResolutionLastModifierIdOk returns a tuple with the ResolutionLastModifierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetResolutionLastModifierIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResolutionLastModifierId) {
		return nil, false
	}
	return o.ResolutionLastModifierId, true
}

// HasResolutionLastModifierId returns a boolean if a field has been set.
func (o *InlineCommentModel) HasResolutionLastModifierId() bool {
	if o != nil && !IsNil(o.ResolutionLastModifierId) {
		return true
	}

	return false
}

// SetResolutionLastModifierId gets a reference to the given string and assigns it to the ResolutionLastModifierId field.
func (o *InlineCommentModel) SetResolutionLastModifierId(v string) {
	o.ResolutionLastModifierId = &v
}

// GetResolutionLastModifiedAt returns the ResolutionLastModifiedAt field value if set, zero value otherwise.
func (o *InlineCommentModel) GetResolutionLastModifiedAt() time.Time {
	if o == nil || IsNil(o.ResolutionLastModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolutionLastModifiedAt
}

// GetResolutionLastModifiedAtOk returns a tuple with the ResolutionLastModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetResolutionLastModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolutionLastModifiedAt) {
		return nil, false
	}
	return o.ResolutionLastModifiedAt, true
}

// HasResolutionLastModifiedAt returns a boolean if a field has been set.
func (o *InlineCommentModel) HasResolutionLastModifiedAt() bool {
	if o != nil && !IsNil(o.ResolutionLastModifiedAt) {
		return true
	}

	return false
}

// SetResolutionLastModifiedAt gets a reference to the given time.Time and assigns it to the ResolutionLastModifiedAt field.
func (o *InlineCommentModel) SetResolutionLastModifiedAt(v time.Time) {
	o.ResolutionLastModifiedAt = &v
}

// GetResolutionStatus returns the ResolutionStatus field value if set, zero value otherwise.
func (o *InlineCommentModel) GetResolutionStatus() InlineCommentResolutionStatus {
	if o == nil || IsNil(o.ResolutionStatus) {
		var ret InlineCommentResolutionStatus
		return ret
	}
	return *o.ResolutionStatus
}

// GetResolutionStatusOk returns a tuple with the ResolutionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetResolutionStatusOk() (*InlineCommentResolutionStatus, bool) {
	if o == nil || IsNil(o.ResolutionStatus) {
		return nil, false
	}
	return o.ResolutionStatus, true
}

// HasResolutionStatus returns a boolean if a field has been set.
func (o *InlineCommentModel) HasResolutionStatus() bool {
	if o != nil && !IsNil(o.ResolutionStatus) {
		return true
	}

	return false
}

// SetResolutionStatus gets a reference to the given InlineCommentResolutionStatus and assigns it to the ResolutionStatus field.
func (o *InlineCommentModel) SetResolutionStatus(v InlineCommentResolutionStatus) {
	o.ResolutionStatus = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *InlineCommentModel) GetProperties() InlineCommentModelProperties {
	if o == nil || IsNil(o.Properties) {
		var ret InlineCommentModelProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetPropertiesOk() (*InlineCommentModelProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *InlineCommentModel) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given InlineCommentModelProperties and assigns it to the Properties field.
func (o *InlineCommentModel) SetProperties(v InlineCommentModelProperties) {
	o.Properties = &v
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *InlineCommentModel) GetOperations() AttachmentSingleOperations {
	if o == nil || IsNil(o.Operations) {
		var ret AttachmentSingleOperations
		return ret
	}
	return *o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetOperationsOk() (*AttachmentSingleOperations, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *InlineCommentModel) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given AttachmentSingleOperations and assigns it to the Operations field.
func (o *InlineCommentModel) SetOperations(v AttachmentSingleOperations) {
	o.Operations = &v
}

// GetLikes returns the Likes field value if set, zero value otherwise.
func (o *InlineCommentModel) GetLikes() BlogPostSingleLikes {
	if o == nil || IsNil(o.Likes) {
		var ret BlogPostSingleLikes
		return ret
	}
	return *o.Likes
}

// GetLikesOk returns a tuple with the Likes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetLikesOk() (*BlogPostSingleLikes, bool) {
	if o == nil || IsNil(o.Likes) {
		return nil, false
	}
	return o.Likes, true
}

// HasLikes returns a boolean if a field has been set.
func (o *InlineCommentModel) HasLikes() bool {
	if o != nil && !IsNil(o.Likes) {
		return true
	}

	return false
}

// SetLikes gets a reference to the given BlogPostSingleLikes and assigns it to the Likes field.
func (o *InlineCommentModel) SetLikes(v BlogPostSingleLikes) {
	o.Likes = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *InlineCommentModel) GetVersions() AttachmentSingleVersions {
	if o == nil || IsNil(o.Versions) {
		var ret AttachmentSingleVersions
		return ret
	}
	return *o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetVersionsOk() (*AttachmentSingleVersions, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *InlineCommentModel) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given AttachmentSingleVersions and assigns it to the Versions field.
func (o *InlineCommentModel) SetVersions(v AttachmentSingleVersions) {
	o.Versions = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *InlineCommentModel) GetLinks() CommentLinks {
	if o == nil || IsNil(o.Links) {
		var ret CommentLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineCommentModel) GetLinksOk() (*CommentLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *InlineCommentModel) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CommentLinks and assigns it to the Links field.
func (o *InlineCommentModel) SetLinks(v CommentLinks) {
	o.Links = &v
}

func (o InlineCommentModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineCommentModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.BlogPostId) {
		toSerialize["blogPostId"] = o.BlogPostId
	}
	if !IsNil(o.PageId) {
		toSerialize["pageId"] = o.PageId
	}
	if !IsNil(o.ParentCommentId) {
		toSerialize["parentCommentId"] = o.ParentCommentId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.ResolutionLastModifierId) {
		toSerialize["resolutionLastModifierId"] = o.ResolutionLastModifierId
	}
	if !IsNil(o.ResolutionLastModifiedAt) {
		toSerialize["resolutionLastModifiedAt"] = o.ResolutionLastModifiedAt
	}
	if !IsNil(o.ResolutionStatus) {
		toSerialize["resolutionStatus"] = o.ResolutionStatus
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}
	if !IsNil(o.Likes) {
		toSerialize["likes"] = o.Likes
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableInlineCommentModel struct {
	value *InlineCommentModel
	isSet bool
}

func (v NullableInlineCommentModel) Get() *InlineCommentModel {
	return v.value
}

func (v *NullableInlineCommentModel) Set(val *InlineCommentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineCommentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineCommentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineCommentModel(val *InlineCommentModel) *NullableInlineCommentModel {
	return &NullableInlineCommentModel{value: val, isSet: true}
}

func (v NullableInlineCommentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineCommentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


