/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"time"
)

// checks if the CreateBlogPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBlogPost200Response{}

// CreateBlogPost200Response struct for CreateBlogPost200Response
type CreateBlogPost200Response struct {
	// ID of the blog post.
	Id *string `json:"id,omitempty"`
	Status *BlogPostContentStatus `json:"status,omitempty"`
	// Title of the blog post.
	Title *string `json:"title,omitempty"`
	// ID of the space the blog post is in.
	SpaceId *string `json:"spaceId,omitempty"`
	// The account ID of the user who created this blog post originally.
	AuthorId *string `json:"authorId,omitempty"`
	// Date and time when the blog post was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Version *Version `json:"version,omitempty"`
	Body *BodySingle `json:"body,omitempty"`
	Labels *AttachmentSingleLabels `json:"labels,omitempty"`
	Properties *AttachmentSingleProperties `json:"properties,omitempty"`
	Operations *AttachmentSingleOperations `json:"operations,omitempty"`
	Likes *BlogPostSingleLikes `json:"likes,omitempty"`
	Versions *AttachmentSingleVersions `json:"versions,omitempty"`
	// Whether the blog post has been favorited by the current user.
	IsFavoritedByCurrentUser *bool `json:"isFavoritedByCurrentUser,omitempty"`
	Links *GetAttachmentById200ResponseAllOfLinks `json:"_links,omitempty"`
}

// NewCreateBlogPost200Response instantiates a new CreateBlogPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBlogPost200Response() *CreateBlogPost200Response {
	this := CreateBlogPost200Response{}
	return &this
}

// NewCreateBlogPost200ResponseWithDefaults instantiates a new CreateBlogPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBlogPost200ResponseWithDefaults() *CreateBlogPost200Response {
	this := CreateBlogPost200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateBlogPost200Response) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetStatus() BlogPostContentStatus {
	if o == nil || IsNil(o.Status) {
		var ret BlogPostContentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetStatusOk() (*BlogPostContentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given BlogPostContentStatus and assigns it to the Status field.
func (o *CreateBlogPost200Response) SetStatus(v BlogPostContentStatus) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateBlogPost200Response) SetTitle(v string) {
	o.Title = &v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *CreateBlogPost200Response) SetSpaceId(v string) {
	o.SpaceId = &v
}

// GetAuthorId returns the AuthorId field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetAuthorId() string {
	if o == nil || IsNil(o.AuthorId) {
		var ret string
		return ret
	}
	return *o.AuthorId
}

// GetAuthorIdOk returns a tuple with the AuthorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetAuthorIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorId) {
		return nil, false
	}
	return o.AuthorId, true
}

// HasAuthorId returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasAuthorId() bool {
	if o != nil && !IsNil(o.AuthorId) {
		return true
	}

	return false
}

// SetAuthorId gets a reference to the given string and assigns it to the AuthorId field.
func (o *CreateBlogPost200Response) SetAuthorId(v string) {
	o.AuthorId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CreateBlogPost200Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetVersion() Version {
	if o == nil || IsNil(o.Version) {
		var ret Version
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetVersionOk() (*Version, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given Version and assigns it to the Version field.
func (o *CreateBlogPost200Response) SetVersion(v Version) {
	o.Version = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetBody() BodySingle {
	if o == nil || IsNil(o.Body) {
		var ret BodySingle
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetBodyOk() (*BodySingle, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given BodySingle and assigns it to the Body field.
func (o *CreateBlogPost200Response) SetBody(v BodySingle) {
	o.Body = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetLabels() AttachmentSingleLabels {
	if o == nil || IsNil(o.Labels) {
		var ret AttachmentSingleLabels
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetLabelsOk() (*AttachmentSingleLabels, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given AttachmentSingleLabels and assigns it to the Labels field.
func (o *CreateBlogPost200Response) SetLabels(v AttachmentSingleLabels) {
	o.Labels = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetProperties() AttachmentSingleProperties {
	if o == nil || IsNil(o.Properties) {
		var ret AttachmentSingleProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetPropertiesOk() (*AttachmentSingleProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given AttachmentSingleProperties and assigns it to the Properties field.
func (o *CreateBlogPost200Response) SetProperties(v AttachmentSingleProperties) {
	o.Properties = &v
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetOperations() AttachmentSingleOperations {
	if o == nil || IsNil(o.Operations) {
		var ret AttachmentSingleOperations
		return ret
	}
	return *o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetOperationsOk() (*AttachmentSingleOperations, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given AttachmentSingleOperations and assigns it to the Operations field.
func (o *CreateBlogPost200Response) SetOperations(v AttachmentSingleOperations) {
	o.Operations = &v
}

// GetLikes returns the Likes field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetLikes() BlogPostSingleLikes {
	if o == nil || IsNil(o.Likes) {
		var ret BlogPostSingleLikes
		return ret
	}
	return *o.Likes
}

// GetLikesOk returns a tuple with the Likes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetLikesOk() (*BlogPostSingleLikes, bool) {
	if o == nil || IsNil(o.Likes) {
		return nil, false
	}
	return o.Likes, true
}

// HasLikes returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasLikes() bool {
	if o != nil && !IsNil(o.Likes) {
		return true
	}

	return false
}

// SetLikes gets a reference to the given BlogPostSingleLikes and assigns it to the Likes field.
func (o *CreateBlogPost200Response) SetLikes(v BlogPostSingleLikes) {
	o.Likes = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetVersions() AttachmentSingleVersions {
	if o == nil || IsNil(o.Versions) {
		var ret AttachmentSingleVersions
		return ret
	}
	return *o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetVersionsOk() (*AttachmentSingleVersions, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given AttachmentSingleVersions and assigns it to the Versions field.
func (o *CreateBlogPost200Response) SetVersions(v AttachmentSingleVersions) {
	o.Versions = &v
}

// GetIsFavoritedByCurrentUser returns the IsFavoritedByCurrentUser field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetIsFavoritedByCurrentUser() bool {
	if o == nil || IsNil(o.IsFavoritedByCurrentUser) {
		var ret bool
		return ret
	}
	return *o.IsFavoritedByCurrentUser
}

// GetIsFavoritedByCurrentUserOk returns a tuple with the IsFavoritedByCurrentUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetIsFavoritedByCurrentUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFavoritedByCurrentUser) {
		return nil, false
	}
	return o.IsFavoritedByCurrentUser, true
}

// HasIsFavoritedByCurrentUser returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasIsFavoritedByCurrentUser() bool {
	if o != nil && !IsNil(o.IsFavoritedByCurrentUser) {
		return true
	}

	return false
}

// SetIsFavoritedByCurrentUser gets a reference to the given bool and assigns it to the IsFavoritedByCurrentUser field.
func (o *CreateBlogPost200Response) SetIsFavoritedByCurrentUser(v bool) {
	o.IsFavoritedByCurrentUser = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CreateBlogPost200Response) GetLinks() GetAttachmentById200ResponseAllOfLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetAttachmentById200ResponseAllOfLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlogPost200Response) GetLinksOk() (*GetAttachmentById200ResponseAllOfLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CreateBlogPost200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetAttachmentById200ResponseAllOfLinks and assigns it to the Links field.
func (o *CreateBlogPost200Response) SetLinks(v GetAttachmentById200ResponseAllOfLinks) {
	o.Links = &v
}

func (o CreateBlogPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBlogPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.SpaceId) {
		toSerialize["spaceId"] = o.SpaceId
	}
	if !IsNil(o.AuthorId) {
		toSerialize["authorId"] = o.AuthorId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}
	if !IsNil(o.Likes) {
		toSerialize["likes"] = o.Likes
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	if !IsNil(o.IsFavoritedByCurrentUser) {
		toSerialize["isFavoritedByCurrentUser"] = o.IsFavoritedByCurrentUser
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCreateBlogPost200Response struct {
	value *CreateBlogPost200Response
	isSet bool
}

func (v NullableCreateBlogPost200Response) Get() *CreateBlogPost200Response {
	return v.value
}

func (v *NullableCreateBlogPost200Response) Set(val *CreateBlogPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBlogPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBlogPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBlogPost200Response(val *CreateBlogPost200Response) *NullableCreateBlogPost200Response {
	return &NullableCreateBlogPost200Response{value: val, isSet: true}
}

func (v NullableCreateBlogPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBlogPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


