/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the UpdateFooterCommentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFooterCommentRequest{}

// UpdateFooterCommentRequest struct for UpdateFooterCommentRequest
type UpdateFooterCommentRequest struct {
	Version *UpdateFooterCommentModelVersion `json:"version,omitempty"`
	Body *CreateFooterCommentModelBody `json:"body,omitempty"`
	Links *GetAttachmentById200ResponseAllOfLinks `json:"_links,omitempty"`
}

// NewUpdateFooterCommentRequest instantiates a new UpdateFooterCommentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFooterCommentRequest() *UpdateFooterCommentRequest {
	this := UpdateFooterCommentRequest{}
	return &this
}

// NewUpdateFooterCommentRequestWithDefaults instantiates a new UpdateFooterCommentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFooterCommentRequestWithDefaults() *UpdateFooterCommentRequest {
	this := UpdateFooterCommentRequest{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateFooterCommentRequest) GetVersion() UpdateFooterCommentModelVersion {
	if o == nil || IsNil(o.Version) {
		var ret UpdateFooterCommentModelVersion
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFooterCommentRequest) GetVersionOk() (*UpdateFooterCommentModelVersion, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateFooterCommentRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given UpdateFooterCommentModelVersion and assigns it to the Version field.
func (o *UpdateFooterCommentRequest) SetVersion(v UpdateFooterCommentModelVersion) {
	o.Version = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *UpdateFooterCommentRequest) GetBody() CreateFooterCommentModelBody {
	if o == nil || IsNil(o.Body) {
		var ret CreateFooterCommentModelBody
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFooterCommentRequest) GetBodyOk() (*CreateFooterCommentModelBody, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *UpdateFooterCommentRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given CreateFooterCommentModelBody and assigns it to the Body field.
func (o *UpdateFooterCommentRequest) SetBody(v CreateFooterCommentModelBody) {
	o.Body = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *UpdateFooterCommentRequest) GetLinks() GetAttachmentById200ResponseAllOfLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetAttachmentById200ResponseAllOfLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFooterCommentRequest) GetLinksOk() (*GetAttachmentById200ResponseAllOfLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *UpdateFooterCommentRequest) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetAttachmentById200ResponseAllOfLinks and assigns it to the Links field.
func (o *UpdateFooterCommentRequest) SetLinks(v GetAttachmentById200ResponseAllOfLinks) {
	o.Links = &v
}

func (o UpdateFooterCommentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFooterCommentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableUpdateFooterCommentRequest struct {
	value *UpdateFooterCommentRequest
	isSet bool
}

func (v NullableUpdateFooterCommentRequest) Get() *UpdateFooterCommentRequest {
	return v.value
}

func (v *NullableUpdateFooterCommentRequest) Set(val *UpdateFooterCommentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFooterCommentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFooterCommentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFooterCommentRequest(val *UpdateFooterCommentRequest) *NullableUpdateFooterCommentRequest {
	return &NullableUpdateFooterCommentRequest{value: val, isSet: true}
}

func (v NullableUpdateFooterCommentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFooterCommentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


