/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"fmt"
)

// AncestorType The type of ancestor.
type AncestorType string

// List of AncestorType
const (
	ANCESTOR_TYPE_PAGE       AncestorType = "page"
	ANCESTOR_TYPE_WHITEBOARD AncestorType = "whiteboard"
	ANCESTOR_TYPE_DATABASE   AncestorType = "database"
	ANCESTOR_TYPE_EMBED      AncestorType = "embed"
	ANCESTOR_TYPE_FOLDER     AncestorType = "folder"
)

// All allowed values of AncestorType enum
var AllowedAncestorTypeEnumValues = []AncestorType{
	"page",
	"whiteboard",
	"database",
	"embed",
	"folder",
}

func (v *AncestorType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AncestorType(value)
	for _, existing := range AllowedAncestorTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AncestorType", value)
}

// NewAncestorTypeFromValue returns a pointer to a valid AncestorType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAncestorTypeFromValue(v string) (*AncestorType, error) {
	ev := AncestorType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AncestorType: valid values are %v", v, AllowedAncestorTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AncestorType) IsValid() bool {
	for _, existing := range AllowedAncestorTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AncestorType value
func (v AncestorType) Ptr() *AncestorType {
	return &v
}

type NullableAncestorType struct {
	value *AncestorType
	isSet bool
}

func (v NullableAncestorType) Get() *AncestorType {
	return v.value
}

func (v *NullableAncestorType) Set(val *AncestorType) {
	v.value = val
	v.isSet = true
}

func (v NullableAncestorType) IsSet() bool {
	return v.isSet
}

func (v *NullableAncestorType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAncestorType(val *AncestorType) *NullableAncestorType {
	return &NullableAncestorType{value: val, isSet: true}
}

func (v NullableAncestorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAncestorType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
