/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the GetSpaceRoleMode200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSpaceRoleMode200Response{}

// GetSpaceRoleMode200Response struct for GetSpaceRoleMode200Response
type GetSpaceRoleMode200Response struct {
	// The space role mode.
	Mode *string `json:"mode,omitempty"`
}

// NewGetSpaceRoleMode200Response instantiates a new GetSpaceRoleMode200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSpaceRoleMode200Response() *GetSpaceRoleMode200Response {
	this := GetSpaceRoleMode200Response{}
	return &this
}

// NewGetSpaceRoleMode200ResponseWithDefaults instantiates a new GetSpaceRoleMode200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSpaceRoleMode200ResponseWithDefaults() *GetSpaceRoleMode200Response {
	this := GetSpaceRoleMode200Response{}
	return &this
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *GetSpaceRoleMode200Response) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSpaceRoleMode200Response) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *GetSpaceRoleMode200Response) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *GetSpaceRoleMode200Response) SetMode(v string) {
	o.Mode = &v
}

func (o GetSpaceRoleMode200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSpaceRoleMode200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	return toSerialize, nil
}

type NullableGetSpaceRoleMode200Response struct {
	value *GetSpaceRoleMode200Response
	isSet bool
}

func (v NullableGetSpaceRoleMode200Response) Get() *GetSpaceRoleMode200Response {
	return v.value
}

func (v *NullableGetSpaceRoleMode200Response) Set(val *GetSpaceRoleMode200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSpaceRoleMode200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSpaceRoleMode200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSpaceRoleMode200Response(val *GetSpaceRoleMode200Response) *NullableGetSpaceRoleMode200Response {
	return &NullableGetSpaceRoleMode200Response{value: val, isSet: true}
}

func (v NullableGetSpaceRoleMode200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSpaceRoleMode200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


