/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the EnableAdminKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableAdminKeyRequest{}

// EnableAdminKeyRequest struct for EnableAdminKeyRequest
type EnableAdminKeyRequest struct {
	// The requested duration of admin key access in minutes, up to a maximum of 60 minutes, after which the issued admin key will automatically expire.
	DurationInMinutes *int32 `json:"durationInMinutes,omitempty"`
}

// NewEnableAdminKeyRequest instantiates a new EnableAdminKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableAdminKeyRequest() *EnableAdminKeyRequest {
	this := EnableAdminKeyRequest{}
	return &this
}

// NewEnableAdminKeyRequestWithDefaults instantiates a new EnableAdminKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableAdminKeyRequestWithDefaults() *EnableAdminKeyRequest {
	this := EnableAdminKeyRequest{}
	return &this
}

// GetDurationInMinutes returns the DurationInMinutes field value if set, zero value otherwise.
func (o *EnableAdminKeyRequest) GetDurationInMinutes() int32 {
	if o == nil || IsNil(o.DurationInMinutes) {
		var ret int32
		return ret
	}
	return *o.DurationInMinutes
}

// GetDurationInMinutesOk returns a tuple with the DurationInMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableAdminKeyRequest) GetDurationInMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationInMinutes) {
		return nil, false
	}
	return o.DurationInMinutes, true
}

// HasDurationInMinutes returns a boolean if a field has been set.
func (o *EnableAdminKeyRequest) HasDurationInMinutes() bool {
	if o != nil && !IsNil(o.DurationInMinutes) {
		return true
	}

	return false
}

// SetDurationInMinutes gets a reference to the given int32 and assigns it to the DurationInMinutes field.
func (o *EnableAdminKeyRequest) SetDurationInMinutes(v int32) {
	o.DurationInMinutes = &v
}

func (o EnableAdminKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableAdminKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DurationInMinutes) {
		toSerialize["durationInMinutes"] = o.DurationInMinutes
	}
	return toSerialize, nil
}

type NullableEnableAdminKeyRequest struct {
	value *EnableAdminKeyRequest
	isSet bool
}

func (v NullableEnableAdminKeyRequest) Get() *EnableAdminKeyRequest {
	return v.value
}

func (v *NullableEnableAdminKeyRequest) Set(val *EnableAdminKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableAdminKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableAdminKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableAdminKeyRequest(val *EnableAdminKeyRequest) *NullableEnableAdminKeyRequest {
	return &NullableEnableAdminKeyRequest{value: val, isSet: true}
}

func (v NullableEnableAdminKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableAdminKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


