/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"fmt"
)

// RoleType The role type.
type RoleType string

// List of RoleType
const (
	ROLE_TYPE_SYSTEM RoleType = "SYSTEM"
	ROLE_TYPE_CUSTOM RoleType = "CUSTOM"
)

// All allowed values of RoleType enum
var AllowedRoleTypeEnumValues = []RoleType{
	"SYSTEM",
	"CUSTOM",
}

func (v *RoleType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RoleType(value)
	for _, existing := range AllowedRoleTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RoleType", value)
}

// NewRoleTypeFromValue returns a pointer to a valid RoleType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRoleTypeFromValue(v string) (*RoleType, error) {
	ev := RoleType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RoleType: valid values are %v", v, AllowedRoleTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RoleType) IsValid() bool {
	for _, existing := range AllowedRoleTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RoleType value
func (v RoleType) Ptr() *RoleType {
	return &v
}

type NullableRoleType struct {
	value *RoleType
	isSet bool
}

func (v NullableRoleType) Get() *RoleType {
	return v.value
}

func (v *NullableRoleType) Set(val *RoleType) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleType) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleType(val *RoleType) *NullableRoleType {
	return &NullableRoleType{value: val, isSet: true}
}

func (v NullableRoleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
