/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateFolderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFolderRequest{}

// CreateFolderRequest struct for CreateFolderRequest
type CreateFolderRequest struct {
	// ID of the space.
	SpaceId string `json:"spaceId"`
	// Title of the folder.
	Title *string `json:"title,omitempty"`
	// The parent content ID of the folder.
	ParentId *string `json:"parentId,omitempty"`
}

type _CreateFolderRequest CreateFolderRequest

// NewCreateFolderRequest instantiates a new CreateFolderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFolderRequest(spaceId string) *CreateFolderRequest {
	this := CreateFolderRequest{}
	this.SpaceId = spaceId
	return &this
}

// NewCreateFolderRequestWithDefaults instantiates a new CreateFolderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFolderRequestWithDefaults() *CreateFolderRequest {
	this := CreateFolderRequest{}
	return &this
}

// GetSpaceId returns the SpaceId field value
func (o *CreateFolderRequest) GetSpaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetSpaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpaceId, true
}

// SetSpaceId sets field value
func (o *CreateFolderRequest) SetSpaceId(v string) {
	o.SpaceId = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateFolderRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateFolderRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateFolderRequest) SetTitle(v string) {
	o.Title = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CreateFolderRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolderRequest) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CreateFolderRequest) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *CreateFolderRequest) SetParentId(v string) {
	o.ParentId = &v
}

func (o CreateFolderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFolderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spaceId"] = o.SpaceId
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	return toSerialize, nil
}

func (o *CreateFolderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spaceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFolderRequest := _CreateFolderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateFolderRequest)

	if err != nil {
		return err
	}

	*o = CreateFolderRequest(varCreateFolderRequest)

	return err
}

type NullableCreateFolderRequest struct {
	value *CreateFolderRequest
	isSet bool
}

func (v NullableCreateFolderRequest) Get() *CreateFolderRequest {
	return v.value
}

func (v *NullableCreateFolderRequest) Set(val *CreateFolderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFolderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFolderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFolderRequest(val *CreateFolderRequest) *NullableCreateFolderRequest {
	return &NullableCreateFolderRequest{value: val, isSet: true}
}

func (v NullableCreateFolderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFolderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


