/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the Integer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Integer{}

// Integer struct for Integer
type Integer struct {
	// The count number
	Count *int64 `json:"count,omitempty"`
}

// NewInteger instantiates a new Integer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInteger() *Integer {
	this := Integer{}
	return &this
}

// NewIntegerWithDefaults instantiates a new Integer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegerWithDefaults() *Integer {
	this := Integer{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *Integer) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Integer) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *Integer) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *Integer) SetCount(v int64) {
	o.Count = &v
}

func (o Integer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Integer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableInteger struct {
	value *Integer
	isSet bool
}

func (v NullableInteger) Get() *Integer {
	return v.value
}

func (v *NullableInteger) Set(val *Integer) {
	v.value = val
	v.isSet = true
}

func (v NullableInteger) IsSet() bool {
	return v.isSet
}

func (v *NullableInteger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInteger(val *Integer) *NullableInteger {
	return &NullableInteger{value: val, isSet: true}
}

func (v NullableInteger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInteger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


