/*
The Confluence Cloud REST API v2

This document describes Confluence's v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the AttachmentSingleVersions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachmentSingleVersions{}

// AttachmentSingleVersions struct for AttachmentSingleVersions
type AttachmentSingleVersions struct {
	Results []Version `json:"results,omitempty"`
	Meta *OptionalFieldMeta `json:"meta,omitempty"`
	Links *OptionalFieldLinks `json:"_links,omitempty"`
}

// NewAttachmentSingleVersions instantiates a new AttachmentSingleVersions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentSingleVersions() *AttachmentSingleVersions {
	this := AttachmentSingleVersions{}
	return &this
}

// NewAttachmentSingleVersionsWithDefaults instantiates a new AttachmentSingleVersions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentSingleVersionsWithDefaults() *AttachmentSingleVersions {
	this := AttachmentSingleVersions{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *AttachmentSingleVersions) GetResults() []Version {
	if o == nil || IsNil(o.Results) {
		var ret []Version
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentSingleVersions) GetResultsOk() ([]Version, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *AttachmentSingleVersions) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Version and assigns it to the Results field.
func (o *AttachmentSingleVersions) SetResults(v []Version) {
	o.Results = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *AttachmentSingleVersions) GetMeta() OptionalFieldMeta {
	if o == nil || IsNil(o.Meta) {
		var ret OptionalFieldMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentSingleVersions) GetMetaOk() (*OptionalFieldMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AttachmentSingleVersions) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given OptionalFieldMeta and assigns it to the Meta field.
func (o *AttachmentSingleVersions) SetMeta(v OptionalFieldMeta) {
	o.Meta = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AttachmentSingleVersions) GetLinks() OptionalFieldLinks {
	if o == nil || IsNil(o.Links) {
		var ret OptionalFieldLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachmentSingleVersions) GetLinksOk() (*OptionalFieldLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AttachmentSingleVersions) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given OptionalFieldLinks and assigns it to the Links field.
func (o *AttachmentSingleVersions) SetLinks(v OptionalFieldLinks) {
	o.Links = &v
}

func (o AttachmentSingleVersions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachmentSingleVersions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableAttachmentSingleVersions struct {
	value *AttachmentSingleVersions
	isSet bool
}

func (v NullableAttachmentSingleVersions) Get() *AttachmentSingleVersions {
	return v.value
}

func (v *NullableAttachmentSingleVersions) Set(val *AttachmentSingleVersions) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentSingleVersions) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentSingleVersions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentSingleVersions(val *AttachmentSingleVersions) *NullableAttachmentSingleVersions {
	return &NullableAttachmentSingleVersions{value: val, isSet: true}
}

func (v NullableAttachmentSingleVersions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentSingleVersions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


