/*
The Confluence Cloud REST API v2

Testing VersionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package swagger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/alexhokl/confluence-cli/swagger"
)

func Test_swagger_VersionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VersionAPIService GetAttachmentVersionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var attachmentId string
		var versionNumber int64

		resp, httpRes, err := apiClient.VersionAPI.GetAttachmentVersionDetails(context.Background(), attachmentId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetAttachmentVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VersionAPI.GetAttachmentVersions(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetBlogPostVersionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var blogpostId int64
		var versionNumber int64

		resp, httpRes, err := apiClient.VersionAPI.GetBlogPostVersionDetails(context.Background(), blogpostId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetBlogPostVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64

		resp, httpRes, err := apiClient.VersionAPI.GetBlogPostVersions(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetCustomContentVersionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customContentId int64
		var versionNumber int64

		resp, httpRes, err := apiClient.VersionAPI.GetCustomContentVersionDetails(context.Background(), customContentId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetCustomContentVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customContentId int64

		resp, httpRes, err := apiClient.VersionAPI.GetCustomContentVersions(context.Background(), customContentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetFooterCommentVersionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64
		var versionNumber int64

		resp, httpRes, err := apiClient.VersionAPI.GetFooterCommentVersionDetails(context.Background(), id, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetFooterCommentVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64

		resp, httpRes, err := apiClient.VersionAPI.GetFooterCommentVersions(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetInlineCommentVersionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64
		var versionNumber int64

		resp, httpRes, err := apiClient.VersionAPI.GetInlineCommentVersionDetails(context.Background(), id, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetInlineCommentVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64

		resp, httpRes, err := apiClient.VersionAPI.GetInlineCommentVersions(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetPageVersionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pageId int64
		var versionNumber int64

		resp, httpRes, err := apiClient.VersionAPI.GetPageVersionDetails(context.Background(), pageId, versionNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VersionAPIService GetPageVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64

		resp, httpRes, err := apiClient.VersionAPI.GetPageVersions(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
