/*
The Confluence Cloud REST API v2

Testing SpacePropertiesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package swagger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/alexhokl/confluence-cli/swagger"
)

func Test_swagger_SpacePropertiesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SpacePropertiesAPIService CreateSpaceProperty", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceId int64

		resp, httpRes, err := apiClient.SpacePropertiesAPI.CreateSpaceProperty(context.Background(), spaceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacePropertiesAPIService DeleteSpacePropertyById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceId int64
		var propertyId int64

		httpRes, err := apiClient.SpacePropertiesAPI.DeleteSpacePropertyById(context.Background(), spaceId, propertyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacePropertiesAPIService GetSpaceProperties", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceId int64

		resp, httpRes, err := apiClient.SpacePropertiesAPI.GetSpaceProperties(context.Background(), spaceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacePropertiesAPIService GetSpacePropertyById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceId int64
		var propertyId int64

		resp, httpRes, err := apiClient.SpacePropertiesAPI.GetSpacePropertyById(context.Background(), spaceId, propertyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacePropertiesAPIService UpdateSpacePropertyById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceId int64
		var propertyId int64

		resp, httpRes, err := apiClient.SpacePropertiesAPI.UpdateSpacePropertyById(context.Background(), spaceId, propertyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
