/*
The Confluence Cloud REST API v2

Testing AppPropertiesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package swagger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/alexhokl/confluence-cli/swagger"
)

func Test_swagger_AppPropertiesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AppPropertiesAPIService DeleteForgeAppProperty", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propertyKey string

		httpRes, err := apiClient.AppPropertiesAPI.DeleteForgeAppProperty(context.Background(), propertyKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppPropertiesAPIService GetForgeAppProperties", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AppPropertiesAPI.GetForgeAppProperties(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppPropertiesAPIService GetForgeAppProperty", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propertyKey string

		resp, httpRes, err := apiClient.AppPropertiesAPI.GetForgeAppProperty(context.Background(), propertyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppPropertiesAPIService PutForgeAppProperty", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propertyKey string

		httpRes, err := apiClient.AppPropertiesAPI.PutForgeAppProperty(context.Background(), propertyKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
